-- Backup de user_profiles.unidade ANTES da padronizacao das grafias
UPDATE user_profiles SET unidade = 'ANTONIO TUPY PINHEIRO, C E-EF M PROFIS' WHERE id = '2TIHdIzVjzPEuftP99FP0adfNGr1';
UPDATE user_profiles SET unidade = 'ANTONIO TUPY PINHEIRO, C E-EF M PROFIS' WHERE id = 'BnxwJWuUf6c1FQrUgX6kVf0vKxY2';
UPDATE user_profiles SET unidade = 'ANTONIO TUPY PINHEIRO, C E-EF M PROFIS' WHERE id = 'HUWU4FZlcVTSK8ixcJFXilxf30M2';
UPDATE user_profiles SET unidade = 'ANITA CANET, C E-EF M P' WHERE id = 'YQTZqbyLSNgTzgn3TaQ3o2Dp6By1';
UPDATE user_profiles SET unidade = 'ANITA CANET, C E-EF M P' WHERE id = 'aib82xxfHaXHJmb8WBxibKpvzz33';
UPDATE user_profiles SET unidade = 'COSTA VIANA, C E-EF M PROFIS N' WHERE id = 'DQL2lBZAc1brU16WWzuIwLBxPy72';
UPDATE user_profiles SET unidade = 'CRISTO REI, C E-EF M PROFIS' WHERE id = '61zmAD21qdgdsCS1BXz2ro0qsMj2';
UPDATE user_profiles SET unidade = 'DECIO DOSSI, C E DR-EF M PROFIS' WHERE id = 'SED6WRKmoKM1vtQiQPKBzYGDft03';
UPDATE user_profiles SET unidade = 'FRANCISCO C MARTINS, C E-M P' WHERE id = 'XYGWEgO6uJhfa6EmvyZth8vY2yO2';
UPDATE user_profiles SET unidade = 'GODOFREDO MACHADO, E E-EF' WHERE id = 'AVYpSApE0qVLA0mIboZH0beIUOC2';
UPDATE user_profiles SET unidade = 'ISABEL L S SOUZA, C E PROFA-EF M PROFIS' WHERE id = 'LrizURC5P9OcFhcxwcQRMO0XntD3';
UPDATE user_profiles SET unidade = 'IVO LEAO, C E-EF M' WHERE id = 'DcPmHO28IyeFRk4F7NUbcO47Vbf1';
UPDATE user_profiles SET unidade = 'JOAO DE OLIVEIRA FRANCO, C E-EF M' WHERE id = 'l6emPOHSK1VpN4OWCdmfh7Bz4xt2';
UPDATE user_profiles SET unidade = 'JOAO MAZZAROTTO, C E-EF M' WHERE id = 'uNUwXV3vGZXgdCR2iW0gqgOc3403';
UPDATE user_profiles SET unidade = 'LIANE MARTA DA COSTA, C E-EF M PROFIS' WHERE id = 'AP5CMdyIEjOsb84MtsyCC0iNONd2';
UPDATE user_profiles SET unidade = 'PAULO FREIRE, C E PROF-E F M N' WHERE id = 'eeFII4afSEX7Xlw6miztKIyKIu83';
UPDATE user_profiles SET unidade = 'SANTO AGOSTINHO, C E-EF M' WHERE id = 'dtkwUL4zQNWxHdRdWQLSHiQ05Ow2';
UPDATE user_profiles SET unidade = 'TARSILA DO AMARAL, C E-EF M PROFIS' WHERE id = 'F2z1NLHjqGTsgv5MbX4YBNnYbOh2';
UPDATE user_profiles SET unidade = 'TEREZA DA S RAMOS, C E PROFA-EF M' WHERE id = 'Xgei8LBL5mRi44LJLOOTNwuj1bI2';
UPDATE user_profiles SET unidade = 'ANTONIO TUPY PINHEIRO, C E-EF M PROFIS' WHERE id = 'A44BhQX6f9UhB0sEGedo8Babtz12';
UPDATE user_profiles SET unidade = 'COSTA VIANA C E EF M PROFIS N' WHERE id = 'Fb98p6b7YHd3S8CEL8oNgt04K7y2';
UPDATE user_profiles SET unidade = 'LIANE MARTA DA COSTA C E EF M' WHERE id = 'VRxbFIDXuwWXF8X6PTL69qSrvY73';
UPDATE user_profiles SET unidade = 'CRISTO REI C E EF M' WHERE id = 'SO8Mzp4rZpXciOmGGpfofmSikHu1';
UPDATE user_profiles SET unidade = 'IVO LEAO C E EF M' WHERE id = '6LHEqKrHhlZLvVEdjveoCf5OFPa2';
UPDATE user_profiles SET unidade = 'PAULO FREIRE C E PROF E F M N' WHERE id = 'jURrnRVS9ZTnuC7lSSnWfRljRyy2';
UPDATE user_profiles SET unidade = 'SANTO AGOSTINHO C E EF M' WHERE id = 'jAX2KwdSIaXQcAqyMo9z4euOhFB3';
UPDATE user_profiles SET unidade = 'TARSILA DO AMARAL C E EF M' WHERE id = 'FwtRdPU0jyfPT3ayrGk0YQ31QaZ2';
UPDATE user_profiles SET unidade = 'TARSILA DO AMARAL C E EF M' WHERE id = 'z0ShFGHFtVYRUB6csnzEWVDLLPE3';
UPDATE user_profiles SET unidade = 'TARSILA DO AMARAL C E EF M' WHERE id = 'GEvcTABfN1U06Rc6Br7K6CYiN1T2';
UPDATE user_profiles SET unidade = 'LIANE MARTA DA COSTA C E EF M' WHERE id = 'm8dvuhFD4wXprTOdoOrJpwvhbHC3';
UPDATE user_profiles SET unidade = 'CRISTO REI C E EF M' WHERE id = 'mpCWiVjg1VbbTY9nSCKetcdlhhF3';
UPDATE user_profiles SET unidade = 'SANTO AGOSTINHO C E EF M' WHERE id = 'IIDoiBekN6ViYzNN050WOiDYuzM2';
UPDATE user_profiles SET unidade = 'DECIO DOSSI C E DR EF M PROFIS' WHERE id = 'tQzGhqEk8ugPzZbOVlbtZ16Q5H32';
UPDATE user_profiles SET unidade = 'TEREZA DA S RAMOS C E PROFA EF M' WHERE id = '8f0DziooY1MoqxU57jSO92afGC03';
UPDATE user_profiles SET unidade = 'CRISTO REI C E EF M' WHERE id = 'vkUZbpid3sMrklfFXem1Ygyg1zn1';
UPDATE user_profiles SET unidade = 'COSTA VIANA C E EF M PROFIS N' WHERE id = 'ookn4XMM6LYB59gs84kwf7uMuTl2';
UPDATE user_profiles SET unidade = 'ANITA CANET C E EF M' WHERE id = 'JrvVu3s1sHVsLHCfMdioKyDjNvF2';
UPDATE user_profiles SET unidade = 'ANITA CANET C E EF M' WHERE id = 'jwoePWmg93RQdndMhGfD4uQwyTJ3';
UPDATE user_profiles SET unidade = 'ANITA CANET C E EF M' WHERE id = 'YWxUzEgYrXcWAgJ95YdkxRyxHZv1';
UPDATE user_profiles SET unidade = 'ANITA CANET C E EF M' WHERE id = 'IxlbOBwNnZMnZw1zDEg55ojrd9W2';
UPDATE user_profiles SET unidade = 'ANITA CANET C E EF M' WHERE id = 'Zq1SehBFcuV8IqPYvIxz9WgsAIi2';
UPDATE user_profiles SET unidade = 'ANITA CANET C E EF M' WHERE id = 'IOjbfBoUHuTylN2ntnnFeXLHxz53';
UPDATE user_profiles SET unidade = 'PAULO FREIRE C E PROF E F M N' WHERE id = 'fbQQUAsMWcQaP33QZ6UbO1fg8Oz1';
UPDATE user_profiles SET unidade = 'TEREZA DA S RAMOS C E PROFA EF M' WHERE id = 'zutt80P6wtOGAlTeOwLfDXbERCR2';
UPDATE user_profiles SET unidade = 'JOAO MAZZAROTTO C E EF M' WHERE id = 'Zcqlnw0uz4Qlf1dy2wxPWcNq2eJ2';
UPDATE user_profiles SET unidade = 'GODOFREDO MACHADO E E EF' WHERE id = 'RUx9WRSUOKODLBmArZT4AWDHkP82';
UPDATE user_profiles SET unidade = 'GODOFREDO MACHADO E E EF' WHERE id = 'rA0n5q58WkNfm9If7nKoluzAYd03';
UPDATE user_profiles SET unidade = 'GODOFREDO MACHADO E E EF' WHERE id = 'hmFdyWOi8eg9zm8J9ELrMOEvqVI2';
UPDATE user_profiles SET unidade = 'TEREZA DA S RAMOS C E PROFA EF M' WHERE id = 'k2qmTDep7wUeHgv5w5jurFBocBm2';
UPDATE user_profiles SET unidade = 'TEREZA DA S RAMOS C E PROFA EF M' WHERE id = 'VoND4rpPutPQHEKb6hfo3tiecRb2';
UPDATE user_profiles SET unidade = 'JOAO DE OLIVEIRA FRANCO C E EF M' WHERE id = 'iIHpzUm81ISbpcmtQIQSmfZBzY83';
UPDATE user_profiles SET unidade = 'TEREZA DA S RAMOS C E PROFA EF M' WHERE id = 'bbMy0rVpfzMdVhOKlFrUi3w4t0h1';
UPDATE user_profiles SET unidade = 'PAULO FREIRE C E PROF E F M N' WHERE id = 'pogRbHGuq1QCDgVQoY7at2b8uuR2';
UPDATE user_profiles SET unidade = 'JOAO DE OLIVEIRA FRANCO C E EF M' WHERE id = 'mHutlRJDJBTMmVGV05TaCAzZlsZ2';
UPDATE user_profiles SET unidade = 'COSTA VIANA C E EF M PROFIS N' WHERE id = 'YJAWn721TvfazEDz0ugpelj5sIA3';
UPDATE user_profiles SET unidade = 'ANITA CANET C E EF M' WHERE id = '9eMiSQCjRgU1SmRNkuqUWZc2jJd2';
UPDATE user_profiles SET unidade = 'PAULO FREIRE C E PROF E F M N' WHERE id = 'QyZPY64CXScXzuW98a0RV4TMW983';
UPDATE user_profiles SET unidade = 'DECIO DOSSI C E DR EF M PROFIS' WHERE id = '53URxDFdzsfZ1cBrQQnuo58CF822';
UPDATE user_profiles SET unidade = 'DECIO DOSSI C E DR EF M PROFIS' WHERE id = 'i2iBHQOBxAbATpGnuVEn1o5fVJc2';
UPDATE user_profiles SET unidade = 'TARSILA DO AMARAL C E EF M' WHERE id = 'puSveNgEGENIs1DLT6VWTB8v5RJ2';
UPDATE user_profiles SET unidade = 'ANITA CANET C E EF M' WHERE id = 'pZ9WC7YyJ8QgmtheuZ7j4esTYUX2';
UPDATE user_profiles SET unidade = 'COSTA VIANA C E EF M PROFIS N' WHERE id = 'hi0ukcAWZ5eepHczMofyDRkf4kg1';
UPDATE user_profiles SET unidade = 'JOAO MAZZAROTTO C E EF M' WHERE id = 'kucswI4jvygaBSqkypu4gS0NGGY2';
UPDATE user_profiles SET unidade = 'ANITA CANET C E EF M' WHERE id = 'hJjMN9Und6NUoZ3ihuG4jvbKHBt1';
UPDATE user_profiles SET unidade = 'JOAO DE OLIVEIRA FRANCO C E EF M' WHERE id = 'x7avgjdKdbb1REhj70z4bBuDnWz2';
UPDATE user_profiles SET unidade = 'TARSILA DO AMARAL C E EF M' WHERE id = 'NlNvF8SIPSScsmw01B1By6kZAm53';
UPDATE user_profiles SET unidade = 'HOMERO B DE BARROS C E EFM ETI' WHERE id = 'Ps9wjx68uFUdHbAknepfJoSf7Gy2';
UPDATE user_profiles SET unidade = 'IVO LEAO C E EF M' WHERE id = 'AHcXKLQ1JvQyvEtcNjNYPBikOdk2';
UPDATE user_profiles SET unidade = 'LIANE MARTA DA COSTA C E EF M' WHERE id = 'CrE9d1ZhrAQorUZxyMsCqdkMqCN2';
UPDATE user_profiles SET unidade = 'HOMERO B DE BARROS C E EFM ETI' WHERE id = 'qZDkz3EUXtST9CfdC6ueQNCGqSc2';
UPDATE user_profiles SET unidade = 'HOMERO B DE BARROS C E EFM ETI' WHERE id = '0zQsYFEAQuTnAMv7cQyX2b418P02';
UPDATE user_profiles SET unidade = 'TEREZA DA S RAMOS C E PROFA EF M' WHERE id = 'Oe6VP8tjTzUU3d0CcXvfyDFtUZZ2';
UPDATE user_profiles SET unidade = 'ANITA CANET C E EF M' WHERE id = 'uUmWFFsSWfef9MjTqHhwkW9d8js1';
UPDATE user_profiles SET unidade = 'COSTA VIANA C E EF M PROFIS N' WHERE id = 'Qrjlm25Z7VT0W0qKRlITOKCYvCx2';
UPDATE user_profiles SET unidade = 'HOMERO B DE BARROS C E EFM ETI' WHERE id = 'rBarxDJWYmYqCFAJ5qihATASrdE3';
UPDATE user_profiles SET unidade = 'TARSILA DO AMARAL C E EF M' WHERE id = 'O0FWlWniBNfX3GyiyQRK3uzmSd83';
UPDATE user_profiles SET unidade = 'TARSILA DO AMARAL C E EF M' WHERE id = 'HUWhnltszjTBKKGEQRy0J4TuVaw2';
UPDATE user_profiles SET unidade = 'JOAO MAZZAROTTO C E EF M' WHERE id = 'lEGRiRyFQFceuNcWLqoLLwmSgKK2';
UPDATE user_profiles SET unidade = 'PAULO FREIRE C E PROF E F M N' WHERE id = 'zjI7P0yg8CUY8Q2N1XOHITaE02j1';
UPDATE user_profiles SET unidade = 'TARSILA DO AMARAL C E EF M' WHERE id = 'HIWA2B2S6Va0E9BoTIxQ5IOd2hr2';
UPDATE user_profiles SET unidade = 'HOMERO B DE BARROS C E EFM ETI' WHERE id = 'BXZqmgOhMAZZtAOhRjxmFj4AQcl2';
UPDATE user_profiles SET unidade = 'ANITA CANET C E EF M' WHERE id = 'GBJDQYteuBWQOaeNLbu1Bj0MUUx2';
UPDATE user_profiles SET unidade = 'ISABEL L S SOUZA C E PROFA EF M' WHERE id = '0cVHg0qi9oMfr5Qa1z2bjJjy2QI3';
UPDATE user_profiles SET unidade = 'JOAO MAZZAROTTO C E EF M' WHERE id = 'JrK9iurSWLYaUv2wmUoG9efdYsI3';
UPDATE user_profiles SET unidade = 'JOAO MAZZAROTTO C E EF M' WHERE id = '1ErabNLUccRVbWp5Vv7MkHxK8le2';
UPDATE user_profiles SET unidade = 'JOAO MAZZAROTTO C E EF M' WHERE id = '3lGFoGJ8SFYHPeqNLreQjzCE6A13';
UPDATE user_profiles SET unidade = 'COSTA VIANA C E EF M PROFIS N' WHERE id = 'CNB9CVX7I0VXYQ6WLkuhram3Lzd2';
UPDATE user_profiles SET unidade = 'COSTA VIANA C E EF M PROFIS N' WHERE id = 'YgoB5Y379jcVEgI7cqQ04YeoOsq2';
UPDATE user_profiles SET unidade = 'ISABEL L S SOUZA C E PROFA EF M' WHERE id = 'Wn3s1Tm1dwUMy1nWJJWM049Nyjs1';
UPDATE user_profiles SET unidade = 'ISABEL L S SOUZA C E PROFA EF M' WHERE id = '9v5ARhoqZafmGsxbfpUg1F6Y6sc2';
UPDATE user_profiles SET unidade = 'HOMERO B DE BARROS C E EFM ETI' WHERE id = 'RPGTU1eE3pZoqHeVmg6IfI2EVQB3';
UPDATE user_profiles SET unidade = 'GILDO A SCHUCK C E PROF EF M ETI N' WHERE id = 'RmtThn8uIpZ0GHa5gPY8j7ziZKI3';
UPDATE user_profiles SET unidade = 'ANITA CANET C E EF M' WHERE id = 'y2RfA8LsqWQhr2gqbY3qKlWnhLA3';
UPDATE user_profiles SET unidade = 'CRISTO REI C E EF M' WHERE id = 'TuyG3jUWUBgAON6tNr1LTpqbsr53';
UPDATE user_profiles SET unidade = 'HOMERO B DE BARROS C E EFM ETI' WHERE id = '2s41lweL2EWEWnz6ThM1Ov9PW7X2';
UPDATE user_profiles SET unidade = 'ANITA CANET C E EF M' WHERE id = 'hnWhb1hI3ZaG8hVLiuHcj88q0Uf1';
UPDATE user_profiles SET unidade = 'HOMERO B DE BARROS C E EFM ETI' WHERE id = 'shyvHUem5pVdDox6RHbFjJRuyxq2';
UPDATE user_profiles SET unidade = 'JOAO MAZZAROTTO C E EF M' WHERE id = 'd9zKAZWdAERPAIp17jGxjDPGy8h1';
UPDATE user_profiles SET unidade = 'PAULO FREIRE C E PROF E F M N' WHERE id = 'y6fRPEXGJYMgyEKeoGxKtx5XZD93';
UPDATE user_profiles SET unidade = 'COSTA VIANA C E EF M PROFIS N' WHERE id = 'FuUhNhCowRUmfy8ZkaWzYd9l99q1';
UPDATE user_profiles SET unidade = 'SANTO AGOSTINHO C E EF M' WHERE id = 'XvAeEhsYGvXf1GftVy0o8EwwRF73';
UPDATE user_profiles SET unidade = 'HOMERO B DE BARROS C E EFM ETI' WHERE id = '3vX9PRJQmnco25B6MtANThNieDb2';
UPDATE user_profiles SET unidade = 'CARNEIRO C E GAL EF M PROFIS' WHERE id = 'BihXtdNOU3bdjygUTo3jKieME3c2';
UPDATE user_profiles SET unidade = 'JOAO MAZZAROTTO C E EF M' WHERE id = 'DOqgVB1B7RXTGKAKigZxzK8Ghv32';
UPDATE user_profiles SET unidade = 'HOMERO B DE BARROS C E EFM ETI' WHERE id = 'j2WWWEeA4kUq1IDacL0lrypYFsE2';
UPDATE user_profiles SET unidade = 'COSTA VIANA C E EF M PROFIS N' WHERE id = 'NKNJSbMGbjf2JfEhKvry83EJoSr2';
UPDATE user_profiles SET unidade = 'JOAO MAZZAROTTO C E EF M' WHERE id = 'zUISJCuTY4UyMiI8aQD5KGq2eAA3';
UPDATE user_profiles SET unidade = 'JOAO DE OLIVEIRA FRANCO C E EF M' WHERE id = 'T5WzS6u9OHQjwygaIkq9KM5La6i1';
UPDATE user_profiles SET unidade = 'LIANE MARTA DA COSTA C E EF M' WHERE id = 'SpObExlNI6bnMKKDnfRzq2ruX3E3';
UPDATE user_profiles SET unidade = 'PAULO FREIRE C E PROF E F M N' WHERE id = 'iyXnEDqoDrdsZbhyG1Xkj0j9BBa2';
UPDATE user_profiles SET unidade = 'GILDO A SCHUCK C E PROF EF M ETI N' WHERE id = '14sVl53R4FR3amRVdI1EUSx4mte2';
UPDATE user_profiles SET unidade = 'ANITA CANET C E EF M' WHERE id = 'Pt0mfGAOwKOVznGnfrjsjcv9tBy2';
UPDATE user_profiles SET unidade = 'JOAO DE OLIVEIRA FRANCO C E EF M' WHERE id = 'FfnvjXXma2VEeFafjhY8kZ289Ii2';
UPDATE user_profiles SET unidade = 'PAULO FREIRE C E PROF E F M N' WHERE id = '3ExJjuFSyHcnseBhCIJe224JYvf1';
UPDATE user_profiles SET unidade = 'ANITA CANET C E EF M' WHERE id = 'v1kThIJ4TqObjUzKGAHKj86vvGc2';
UPDATE user_profiles SET unidade = 'ANITA CANET C E EF M' WHERE id = 'XfDRTGLUOJTzRgfwo1JaN2IeuLE2';
UPDATE user_profiles SET unidade = 'ANTONIO TUPY PINHEIRO C E EF M' WHERE id = 'eHDoTiazdrXamtbhAwLtWQdZ8El2';
UPDATE user_profiles SET unidade = 'ANTONIO TUPY PINHEIRO C E EF M' WHERE id = 'rrS0tfoCyNNYmpMV5ETVD7OH5ba2';
UPDATE user_profiles SET unidade = 'JOAO MAZZAROTTO C E EF M' WHERE id = 'HAU3GlcJJBdywFfkW3JCiVBfo0x1';
UPDATE user_profiles SET unidade = 'PAULO FREIRE C E PROF E F M N' WHERE id = 'gVXXNUtwlIbZHqAzC9qxvGe6inz2';
UPDATE user_profiles SET unidade = 'TARSILA DO AMARAL C E EF M' WHERE id = 'klSLyzQ94fTcINlUAPUi8uYN48P2';
UPDATE user_profiles SET unidade = 'FRANCISCO C MARTINS C E EM PROF' WHERE id = 'qfyAKjTgynOXkPCilfaRfwpMci23';
UPDATE user_profiles SET unidade = 'IVO LEAO C E EF M' WHERE id = 'Ux0JgKPvU2QJhKUezrjAxENZjqd2';
UPDATE user_profiles SET unidade = 'LIANE MARTA DA COSTA C E EF M' WHERE id = 'kP4fshArSfX0YDcgshPCdm1DgQX2';
UPDATE user_profiles SET unidade = 'LIANE MARTA DA COSTA C E EF M' WHERE id = 'd1Ll5iHkSzScSlDaJPzQP20wLEj1';
UPDATE user_profiles SET unidade = 'CARNEIRO C E GAL EF M PROFIS' WHERE id = 'IBlwYs9aIiUzRBGwjNd4P5Onbmo1';
UPDATE user_profiles SET unidade = 'COSTA VIANA C E EF M PROFIS N' WHERE id = 'Wk4rOHYa3kRs9Vv8R8PK5zcwBRt2';
UPDATE user_profiles SET unidade = 'COSTA VIANA C E EF M PROFIS N' WHERE id = 'FNV1NV0hOvQZQrxHYLD94dOGrsJ2';
UPDATE user_profiles SET unidade = 'FRANCISCO C MARTINS C E EM PROF' WHERE id = 'CXJfSjr80dT1RXZN1glPMaHZPvy1';
UPDATE user_profiles SET unidade = 'TEREZA DA S RAMOS C E PROFA EF M' WHERE id = 'Z9GJ35FpH7O6GEawaPKrSLUdGUx1';
UPDATE user_profiles SET unidade = 'COSTA VIANA C E EF M PROFIS N' WHERE id = 'cy9kdGjzJvU8Cb91IerEZqVGk5I3';
UPDATE user_profiles SET unidade = 'IVO LEAO C E EF M' WHERE id = 's8oqCYUqObTa493gDe6tIUS72Ua2';
UPDATE user_profiles SET unidade = 'FRANCISCO C MARTINS C E EM PROF' WHERE id = 'eAwfjUBAJgRngvaBKSOU3q0TTbq1';
UPDATE user_profiles SET unidade = 'LIANE MARTA DA COSTA C E EF M' WHERE id = 'JEahaJlJiCMIexeWqezyv4XX8UN2';
UPDATE user_profiles SET unidade = 'LIANE MARTA DA COSTA C E EF M' WHERE id = 'h4ASf4fzJRTZ9oYdMTx0XyejmhP2';
UPDATE user_profiles SET unidade = 'IVO LEAO C E EF M' WHERE id = 'L2smFG22VhUZMDqbsGBobhAtsJz1';
UPDATE user_profiles SET unidade = 'JOAO DE OLIVEIRA FRANCO C E EF M' WHERE id = '3ZRUgGRru4NuEAwU7dPSIhsVRME3';
UPDATE user_profiles SET unidade = 'CARNEIRO C E GAL EF M PROFIS' WHERE id = '7dzF1wpzJ6ZdVcwvbkkBh9vhRO23';
UPDATE user_profiles SET unidade = 'FRANCISCO C MARTINS C E EM PROF' WHERE id = 'kykeAG7IGOdOBYSFs3iqhL6Gw5D2';
UPDATE user_profiles SET unidade = 'JOAO DE OLIVEIRA FRANCO C E EF M' WHERE id = 'dDtpHlghoCTGbhbVEnXXB1i9NQ93';
UPDATE user_profiles SET unidade = 'FRANCISCO C MARTINS C E EM PROF' WHERE id = '6qdFkOEBRNhNuQWIub9LfDsFO3E3';
UPDATE user_profiles SET unidade = 'TEREZA DA S RAMOS C E PROFA EF M' WHERE id = 'rq0lLd5nkqQwjEJ21aXkJR3lwAk1';
UPDATE user_profiles SET unidade = 'ANTONIO TUPY PINHEIRO C E EF M' WHERE id = 'JbgUxPWu9DYS4zYxKc482UzmJ7G3';
UPDATE user_profiles SET unidade = 'ANTONIO TUPY PINHEIRO C E EF M' WHERE id = 'aqhRJByGhTP64muF7YpQS0c4Z962';
UPDATE user_profiles SET unidade = 'CARNEIRO C E GAL EF M PROFIS' WHERE id = 'TGvxa3MqiFcCoct5oL30t7bvLWo2';
UPDATE user_profiles SET unidade = 'FRANCISCO C MARTINS C E EM PROF' WHERE id = 'KCw3FdcGv4aBA4y0qYlDzKBFTzy2';
UPDATE user_profiles SET unidade = 'DECIO DOSSI C E DR EF M PROFIS' WHERE id = 'uTQPmnlHj1XJWf2NTyvwSEUBAwG2';
UPDATE user_profiles SET unidade = 'GILDO A SCHUCK C E PROF EF M ETI N' WHERE id = 'O4j98Otm6mYKyVWD3ZPKx9FtQvp2';
UPDATE user_profiles SET unidade = 'FRANCISCO C MARTINS C E EM PROF' WHERE id = 'd7yz01lSFIfwiwdTnLFhYPSEN893';
UPDATE user_profiles SET unidade = 'FRANCISCO C MARTINS C E EM PROF' WHERE id = 'IIXm8KqZ2chxx0Y4cjPXe7UEAou1';
UPDATE user_profiles SET unidade = 'COSTA VIANA C E EF M PROFIS N' WHERE id = 'regwrdna1qaqhqswaniLq42lCvm2';
UPDATE user_profiles SET unidade = 'FRANCISCO C MARTINS C E EM PROF' WHERE id = 'o3hlggCNRHW9gWXPWvNsTDY2zAw1';
UPDATE user_profiles SET unidade = 'LIANE MARTA DA COSTA C E EF M' WHERE id = 'Lyi4MFnQeqPodzsRVouDRseeuaZ2';
UPDATE user_profiles SET unidade = 'ANTONIO TUPY PINHEIRO, C E-EF M PROFIS' WHERE id = 'Jr3swEs3WJXF8xeQih3YrkZb8372';
UPDATE user_profiles SET unidade = 'CARNEIRO C E GAL EF M PROFIS' WHERE id = 'eXD9fBbuyWcs3SlaAYIi8xKuWWs2';
UPDATE user_profiles SET unidade = 'ANITA CANET C E EF M' WHERE id = 'p5U9NcJ4EDgNM6UPEJxRFdXKoj22';
UPDATE user_profiles SET unidade = 'IVO LEAO C E EF M' WHERE id = 'dXsDL01WKRQGD1XH0CcdjGhRgGx2';
UPDATE user_profiles SET unidade = 'ANTONIO TUPY PINHEIRO C E EF M' WHERE id = 'WInkyMOEZtX31ZpEfUjFQXJY0Ie2';
UPDATE user_profiles SET unidade = 'TEREZA DA S RAMOS C E PROFA EF M' WHERE id = 'IsvNbPFovWeAMmSK9wzkC3Qek5F3';
