/*
  # componentes_habilidades: adiciona tipo_prova e rede + recarga a partir da planilha

  Contexto:
    A tabela `componentes_habilidades` passa a ser a REFERENCIA CANONICA de descritores das
    3 avaliacoes (prova-parana, mais, parceiro). Antes ela tinha ~160 linhas que, na pratica,
    eram apenas os descritores do 'parceiro' (incompletos).

  Mudancas:
    1. Adiciona colunas `tipo_prova` (prova-parana|mais|parceiro) e `rede`.
    2. Recarrega a tabela com 484 descritores distintos extraidos da planilha
       "Descritores Provas SAEP" / aba "Copia de Descritores".
       - Deduplicacao por (tipo_prova, ano_escolar, componente, posicao) -> descricao estavel.
       - As 3 edicoes "PARANA RECOMPOSICAO" colapsam em tipo_prova='prova-parana';
         a habilidade/habilidade_posicao guardada e a da edicao mais recente (2026).
       - Mapeamentos: ENSINO MEDIO 1a/2a/3a SERIE -> 1o/2o/3o ano; FUNDAMENTAL 6o..9o -> 6o..9o ano.
    3. Chave natural UNIQUE (tipo_prova, ano_escolar, componente, posicao) + indice de lookup.

  IMPORTANTE: rode ANTES da migration de FK (20260712120100), pois a recarga gera novos id.
*/

ALTER TABLE componentes_habilidades
  ADD COLUMN IF NOT EXISTS tipo_prova text,
  ADD COLUMN IF NOT EXISTS rede text;

-- Recarga completa a partir da planilha (484 descritores distintos)
DELETE FROM componentes_habilidades;

INSERT INTO componentes_habilidades
  (ano_escolar, componente, tipo_prova, rede, habilidade_posicao, habilidade, posicao, descricao)
VALUES
('7º ano','LP','parceiro','ESTADUAL','H 07 (D025_P)','H07','D025_P','Reconhecer efeitos de sentido decorrentes do uso ou função da pontuação e de outras notações.'),
('8º ano','LP','parceiro','ESTADUAL','H 06 (D025_P)','H06','D025_P','Reconhecer efeitos de sentido decorrentes do uso ou função da pontuação e de outras notações.'),
('9º ano','LP','parceiro','ESTADUAL','H 06 (D025_P)','H06','D025_P','Reconhecer efeitos de sentido decorrentes do uso ou função da pontuação e de outras notações.'),
('2º ano','LP','parceiro','ESTADUAL','H 05 (D025_P)','H05','D025_P','Reconhecer efeitos de sentido decorrentes do uso ou função da pontuação e de outras notações.'),
('3º ano','LP','parceiro','ESTADUAL','H 07 (D025_P)','H07','D025_P','Reconhecer efeitos de sentido decorrentes do uso ou função da pontuação e de outras notações.'),
('6º ano','LP','parceiro','ESTADUAL','H 08 (D037_P)','H08','D037_P','Reconhecer as relações entre partes de um texto, identificando os recursos coesivos que contribuem para a sua continuidade.'),
('7º ano','LP','parceiro','ESTADUAL','H 10 (D037_P)','H10','D037_P','Reconhecer as relações entre partes de um texto, identificando os recursos coesivos que contribuem para a sua continuidade.'),
('8º ano','LP','parceiro','ESTADUAL','H 09 (D037_P)','H09','D037_P','Reconhecer as relações entre partes de um texto, identificando os recursos coesivos que contribuem para a sua continuidade.'),
('9º ano','LP','parceiro','ESTADUAL','H 10 (D037_P)','H10','D037_P','Reconhecer as relações entre partes de um texto, identificando os recursos coesivos que contribuem para a sua continuidade.'),
('1º ano','LP','parceiro','ESTADUAL','H 07 (D037_P)','H07','D037_P','Reconhecer as relações entre partes de um texto, identificando os recursos coesivos que contribuem para a sua continuidade.'),
('2º ano','LP','parceiro','ESTADUAL','H 08 (D037_P)','H08','D037_P','Reconhecer as relações entre partes de um texto, identificando os recursos coesivos que contribuem para a sua continuidade.'),
('3º ano','LP','parceiro','ESTADUAL','H 11 (D037_P)','H11','D037_P','Reconhecer as relações entre partes de um texto, identificando os recursos coesivos que contribuem para a sua continuidade.'),
('6º ano','LP','parceiro','ESTADUAL','H 03 (D021_P)','H03','D021_P','Localizar informação explícita.'),
('7º ano','LP','parceiro','ESTADUAL','H 03 (D021_P)','H03','D021_P','Localizar informação explícita.'),
('8º ano','LP','parceiro','ESTADUAL','H 03 (D021_P)','H03','D021_P','Localizar informação explícita.'),
('9º ano','LP','parceiro','ESTADUAL','H 03 (D021_P)','H03','D021_P','Localizar informação explícita.'),
('3º ano','LP','parceiro','ESTADUAL','H 03 (D021_P)','H03','D021_P','Localizar informação explícita.'),
('6º ano','LP','parceiro','ESTADUAL','H 06 (D028_P)','H06','D028_P','Reconhecer o assunto de um texto lido.'),
('7º ano','LP','parceiro','ESTADUAL','H 08 (D028_P)','H08','D028_P','Reconhecer o assunto de um texto lido.'),
('8º ano','LP','parceiro','ESTADUAL','H 07 (D028_P)','H07','D028_P','Reconhecer o assunto de um texto lido.'),
('9º ano','LP','parceiro','ESTADUAL','H 07 (D028_P)','H07','D028_P','Reconhecer o assunto de um texto lido.'),
('1º ano','LP','parceiro','ESTADUAL','H 05 (D028_P)','H05','D028_P','Reconhecer o assunto de um texto lido.'),
('2º ano','LP','parceiro','ESTADUAL','H 06 (D028_P)','H06','D028_P','Reconhecer o assunto de um texto lido.'),
('3º ano','LP','parceiro','ESTADUAL','H 08 (D028_P)','H08','D028_P','Reconhecer o assunto de um texto lido.'),
('6º ano','LP','parceiro','ESTADUAL','H 05 (D023_P)','H05','D023_P','Inferir informações em textos.'),
('7º ano','LP','parceiro','ESTADUAL','H 05 (D023_P)','H05','D023_P','Inferir informações em textos.'),
('8º ano','LP','parceiro','ESTADUAL','H 04 (D023_P)','H04','D023_P','Inferir informações em textos.'),
('9º ano','LP','parceiro','ESTADUAL','H 04 (D023_P)','H04','D023_P','Inferir informações em textos.'),
('1º ano','LP','parceiro','ESTADUAL','H 03 (D023_P)','H03','D023_P','Inferir informações em textos.'),
('2º ano','LP','parceiro','ESTADUAL','H 03 (D023_P)','H03','D023_P','Inferir informações em textos.'),
('3º ano','LP','parceiro','ESTADUAL','H 05 (D023_P)','H05','D023_P','Inferir informações em textos.'),
('6º ano','LP','parceiro','ESTADUAL','H 04 (D022_P)','H04','D022_P','Inferir o sentido de palavra ou expressão a partir do contexto.'),
('7º ano','LP','parceiro','ESTADUAL','H 04 (D022_P)','H04','D022_P','Inferir o sentido de palavra ou expressão a partir do contexto.'),
('3º ano','LP','parceiro','ESTADUAL','H 04 (D022_P)','H04','D022_P','Inferir o sentido de palavra ou expressão a partir do contexto.'),
('6º ano','LP','parceiro','ESTADUAL','H 07 (D030_P)','H07','D030_P','Reconhecer os elementos que compõem uma narrativa e o conflito gerador.'),
('7º ano','LP','parceiro','ESTADUAL','H 09 (D030_P)','H09','D030_P','Reconhecer os elementos que compõem uma narrativa e o conflito gerador.'),
('8º ano','LP','parceiro','ESTADUAL','H 08 (D030_P)','H08','D030_P','Reconhecer os elementos que compõem uma narrativa e o conflito gerador.'),
('9º ano','LP','parceiro','ESTADUAL','H 08 (D030_P)','H08','D030_P','Reconhecer os elementos que compõem uma narrativa e o conflito gerador.'),
('3º ano','LP','parceiro','ESTADUAL','H 09 (D030_P)','H09','D030_P','Reconhecer os elementos que compõem uma narrativa e o conflito gerador.'),
('6º ano','LP','parceiro','ESTADUAL','H 02 (D019_P)','H02','D019_P','Reconhecer formas de tratar uma informação na comparação de textos que tratam do mesmo tema.'),
('7º ano','LP','parceiro','ESTADUAL','H 02 (D019_P)','H02','D019_P','Reconhecer formas de tratar uma informação na comparação de textos que tratam do mesmo tema.'),
('8º ano','LP','parceiro','ESTADUAL','H 02 (D019_P)','H02','D019_P','Reconhecer formas de tratar uma informação na comparação de textos que tratam do mesmo tema.'),
('9º ano','LP','parceiro','ESTADUAL','H 02 (D019_P)','H02','D019_P','Reconhecer formas de tratar uma informação na comparação de textos que tratam do mesmo tema.'),
('1º ano','LP','parceiro','ESTADUAL','H 02 (D019_P)','H02','D019_P','Reconhecer formas de tratar uma informação na comparação de textos que tratam do mesmo tema.'),
('2º ano','LP','parceiro','ESTADUAL','H 02 (D019_P)','H02','D019_P','Reconhecer formas de tratar uma informação na comparação de textos que tratam do mesmo tema.'),
('3º ano','LP','parceiro','ESTADUAL','H 02 (D019_P)','H02','D019_P','Reconhecer formas de tratar uma informação na comparação de textos que tratam do mesmo tema.'),
('6º ano','LP','parceiro','ESTADUAL','H 09 (D038_P)','H09','D038_P','Distinguir um fato da opinião.'),
('7º ano','LP','parceiro','ESTADUAL','H 11 (D038_P)','H11','D038_P','Distinguir um fato da opinião.'),
('8º ano','LP','parceiro','ESTADUAL','H 10 (D038_P)','H10','D038_P','Distinguir um fato da opinião.'),
('9º ano','LP','parceiro','ESTADUAL','H 11 (D038_P)','H11','D038_P','Distinguir um fato da opinião.'),
('1º ano','LP','parceiro','ESTADUAL','H 08 (D038_P)','H08','D038_P','Distinguir um fato da opinião.'),
('2º ano','LP','parceiro','ESTADUAL','H 09 (D038_P)','H09','D038_P','Distinguir um fato da opinião.'),
('3º ano','LP','parceiro','ESTADUAL','H 12 (D038_P)','H12','D038_P','Distinguir um fato da opinião.'),
('9º ano','LP','parceiro','ESTADUAL','H 09 (D032_P)','H09','D032_P','Identificar a tese de um texto.'),
('1º ano','LP','parceiro','ESTADUAL','H 06 (D032_P)','H06','D032_P','Identificar a tese de um texto.'),
('2º ano','LP','parceiro','ESTADUAL','H 07 (D032_P)','H07','D032_P','Identificar a tese de um texto.'),
('3º ano','LP','parceiro','ESTADUAL','H 10 (D032_P)','H10','D032_P','Identificar a tese de um texto.'),
('8º ano','LP','parceiro','ESTADUAL','H 14 (D114_P)','H14','D114_P','Reconhecer efeitos de sentido decorrentes da exploração de recursos linguísticos.'),
('3º ano','LP','parceiro','ESTADUAL','H 16 (D114_P)','H16','D114_P','Reconhecer efeitos de sentido decorrentes da exploração de recursos linguísticos.'),
('7º ano','LP','parceiro','ESTADUAL','H 06 (D024_P)','H06','D024_P','Reconhecer efeito de humor ou de ironia em um texto.'),
('8º ano','LP','parceiro','ESTADUAL','H 05 (D024_P)','H05','D024_P','Reconhecer efeito de humor ou de ironia em um texto.'),
('9º ano','LP','parceiro','ESTADUAL','H 05 (D024_P)','H05','D024_P','Reconhecer efeito de humor ou de ironia em um texto.'),
('1º ano','LP','parceiro','ESTADUAL','H 04 (D024_P)','H04','D024_P','Reconhecer efeito de humor ou de ironia em um texto.'),
('2º ano','LP','parceiro','ESTADUAL','H 04 (D024_P)','H04','D024_P','Reconhecer efeito de humor ou de ironia em um texto.'),
('3º ano','LP','parceiro','ESTADUAL','H 06 (D024_P)','H06','D024_P','Reconhecer efeito de humor ou de ironia em um texto.'),
('7º ano','LP','parceiro','ESTADUAL','H 12 (D039_P)','H12','D039_P','Reconhecer o sentido das relações lógico-discursivas em um texto.'),
('8º ano','LP','parceiro','ESTADUAL','H 11 (D039_P)','H11','D039_P','Reconhecer o sentido das relações lógico-discursivas em um texto.'),
('9º ano','LP','parceiro','ESTADUAL','H 12 (D039_P)','H12','D039_P','Reconhecer o sentido das relações lógico-discursivas em um texto.'),
('2º ano','LP','parceiro','ESTADUAL','H 10 (D039_P)','H10','D039_P','Reconhecer o sentido das relações lógico-discursivas em um texto.'),
('3º ano','LP','parceiro','ESTADUAL','H 13 (D039_P)','H13','D039_P','Reconhecer o sentido das relações lógico-discursivas em um texto.'),
('8º ano','LP','parceiro','ESTADUAL','H 13 (D044_P)','H13','D044_P','Identificar marcas linguísticas em um texto.'),
('6º ano','LP','parceiro','ESTADUAL','H 01 (D016_P)','H01','D016_P','Identificar a finalidade de textos de diferentes gêneros.'),
('7º ano','LP','parceiro','ESTADUAL','H 01 (D016_P)','H01','D016_P','Identificar a finalidade de textos de diferentes gêneros.'),
('8º ano','LP','parceiro','ESTADUAL','H 01 (D016_P)','H01','D016_P','Identificar a finalidade de textos de diferentes gêneros.'),
('9º ano','LP','parceiro','ESTADUAL','H 01 (D016_P)','H01','D016_P','Identificar a finalidade de textos de diferentes gêneros.'),
('1º ano','LP','parceiro','ESTADUAL','H 01 (D016_P)','H01','D016_P','Identificar a finalidade de textos de diferentes gêneros.'),
('2º ano','LP','parceiro','ESTADUAL','H 01 (D016_P)','H01','D016_P','Identificar a finalidade de textos de diferentes gêneros.'),
('3º ano','LP','parceiro','ESTADUAL','H 01 (D016_P)','H01','D016_P','Identificar a finalidade de textos de diferentes gêneros.'),
('8º ano','LP','parceiro','ESTADUAL','H 12 (D043_P)','H12','D043_P','Reconhecer recursos estilísticos utilizados na construção de textos.'),
('9º ano','LP','parceiro','ESTADUAL','H 13 (D043_P)','H13','D043_P','Reconhecer recursos estilísticos utilizados na construção de textos.'),
('1º ano','LP','parceiro','ESTADUAL','H 10 (D043_P)','H10','D043_P','Reconhecer recursos estilísticos utilizados na construção de textos.'),
('2º ano','LP','parceiro','ESTADUAL','H 11 (D043_P)','H11','D043_P','Reconhecer recursos estilísticos utilizados na construção de textos.'),
('3º ano','LP','parceiro','ESTADUAL','H 14 (D043_P)','H14','D043_P','Reconhecer recursos estilísticos utilizados na construção de textos.'),
('7º ano','LP','parceiro','ESTADUAL','H 14 (D114_P)','H14','D114_P','Reconhecer efeitos de sentido decorrentes da exploração de recursos linguísticos.'),
('2º ano','LP','parceiro','ESTADUAL','H 13 (D114_P)','H13','D114_P','Reconhecer efeitos de sentido decorrentes da exploração de recursos linguísticos.'),
('3º ano','LP','prova-parana','ESTADUAL','H 13 (D061_P)','H13','D061_P','Estabelecer relação causa/consequência entre partes e elementos do texto.'),
('9º ano','LP','prova-parana','ESTADUAL','H 09 (D037_P)','H09','D037_P','Reconhecer as relações entre partes de um texto, identificando os recursos coesivos que contribuem para a sua continuidade.'),
('3º ano','LP','prova-parana','ESTADUAL','H 08 (D037_P)','H08','D037_P','Reconhecer as relações entre partes de um texto, identificando os recursos coesivos que contribuem para a sua continuidade.'),
('3º ano','LP','prova-parana','ESTADUAL','H 07 (D033_P)','H07','D033_P','Reconhecer posições distintas relativas ao mesmo fato ou mesmo tema.'),
('9º ano','LP','prova-parana','ESTADUAL','H 15 (D103_P)','H15','D103_P','Identificar as marcas linguísticas que evidenciam o locutor e o interlocutor de um texto.'),
('9º ano','LP','prova-parana','ESTADUAL','H 06 (D028_P)','H06','D028_P','Reconhecer o assunto de um texto lido.'),
('3º ano','LP','prova-parana','ESTADUAL','H 05 (D027_P)','H05','D027_P','Distinguir ideias centrais de secundárias ou tópicos e subtópicos em um dado gênero textual.'),
('9º ano','LP','prova-parana','ESTADUAL','H 04 (D023_P)','H04','D023_P','Inferir informações em textos.'),
('3º ano','LP','prova-parana','ESTADUAL','H 03 (D023_P)','H03','D023_P','Inferir informações em textos.'),
('9º ano','LP','prova-parana','ESTADUAL','H 03 (D022_P)','H03','D022_P','Inferir o sentido de palavra ou expressão a partir do contexto.'),
('9º ano','LP','prova-parana','ESTADUAL','H 07 (D030_P)','H07','D030_P','Reconhecer os elementos que compõem uma narrativa e o conflito gerador.'),
('9º ano','LP','prova-parana','ESTADUAL','H 02 (D019_P)','H02','D019_P','Reconhecer formas de tratar uma informação na comparação de textos que tratam do mesmo tema.'),
('3º ano','LP','prova-parana','ESTADUAL','H 02 (D019_P)','H02','D019_P','Reconhecer formas de tratar uma informação na comparação de textos que tratam do mesmo tema.'),
('9º ano','LP','prova-parana','ESTADUAL','H 10 (D038_P)','H10','D038_P','Distinguir um fato da opinião.'),
('3º ano','LP','prova-parana','ESTADUAL','H 09 (D038_P)','H09','D038_P','Distinguir um fato da opinião.'),
('9º ano','LP','prova-parana','ESTADUAL','H 13 (D055_P)','H13','D055_P','Estabelecer relação entre a tese e os argumentos oferecidos para sustentá-la.'),
('9º ano','LP','prova-parana','ESTADUAL','H 08 (D032_P)','H08','D032_P','Identificar a tese de um texto.'),
('3º ano','LP','prova-parana','ESTADUAL','H 12 (D055_P)','H12','D055_P','Estabelecer relação entre a tese e os argumentos oferecidos para sustentá-la.'),
('3º ano','LP','prova-parana','ESTADUAL','H 06 (D032_P)','H06','D032_P','Identificar a tese de um texto.'),
('9º ano','LP','prova-parana','ESTADUAL','H 14 (D102_P)','H14','D102_P','Reconhecer o efeito de sentido decorrente da exploração de recursos ortográficos e/ou morfossintáticos.'),
('3º ano','LP','prova-parana','ESTADUAL','H 14 (D102_P)','H14','D102_P','Reconhecer o efeito de sentido decorrente da exploração de recursos ortográficos e/ou morfossintáticos.'),
('9º ano','LP','prova-parana','ESTADUAL','H 05 (D024_P)','H05','D024_P','Reconhecer efeito de humor ou de ironia em um texto.'),
('3º ano','LP','prova-parana','ESTADUAL','H 04 (D024_P)','H04','D024_P','Reconhecer efeito de humor ou de ironia em um texto.'),
('9º ano','LP','prova-parana','ESTADUAL','H 11 (D039_P)','H11','D039_P','Reconhecer o sentido das relações lógico-discursivas em um texto.'),
('3º ano','LP','prova-parana','ESTADUAL','H 10 (D039_P)','H10','D039_P','Reconhecer o sentido das relações lógico-discursivas em um texto.'),
('9º ano','LP','prova-parana','ESTADUAL','H 01 (D016_P)','H01','D016_P','Identificar a finalidade de textos de diferentes gêneros.'),
('3º ano','LP','prova-parana','ESTADUAL','H 01 (D016_P)','H01','D016_P','Identificar a finalidade de textos de diferentes gêneros.'),
('9º ano','LP','prova-parana','ESTADUAL','H 12 (D053_P)','H12','D053_P','Reconhecer o efeito de sentido decorrente da escolha de uma determinada palavra ou expressão.'),
('3º ano','LP','prova-parana','ESTADUAL','H 11 (D053_P)','H11','D053_P','Reconhecer o efeito de sentido decorrente da escolha de uma determinada palavra ou expressão.'),
('3º ano','LP','prova-parana','ESTADUAL','H 15 (D103_P)','H15','D103_P','Identificar as marcas linguísticas que evidenciam o locutor e o interlocutor de um texto.'),
('6º ano','LP','prova-parana','ESTADUAL','H 07 (D025_P)','H07','D025_P','Reconhecer efeitos de sentido decorrentes do uso ou função da pontuação e de outras notações.'),
('6º ano','LP','prova-parana','ESTADUAL','H 14 (D061_P)','H14','D061_P','Estabelecer relação causa/consequência entre partes e elementos do texto.'),
('6º ano','LP','prova-parana','ESTADUAL','H 10 (D037_P)','H10','D037_P','Reconhecer as relações entre partes de um texto, identificando os recursos coesivos que contribuem para a sua continuidade.'),
('6º ano','LP','prova-parana','ESTADUAL','H 03 (D021_P)','H03','D021_P','Localizar informação explícita.'),
('6º ano','LP','prova-parana','ESTADUAL','H 15 (D103_P)','H15','D103_P','Identificar as marcas linguísticas que evidenciam o locutor e o interlocutor de um texto.'),
('6º ano','LP','prova-parana','ESTADUAL','H 08 (D028_P)','H08','D028_P','Reconhecer o assunto de um texto lido.'),
('6º ano','LP','prova-parana','ESTADUAL','H 05 (D023_P)','H05','D023_P','Inferir informações em textos.'),
('6º ano','LP','prova-parana','ESTADUAL','H 04 (D022_P)','H04','D022_P','Inferir o sentido de palavra ou expressão a partir do contexto.'),
('6º ano','LP','prova-parana','ESTADUAL','H 09 (D030_P)','H09','D030_P','Reconhecer os elementos que compõem uma narrativa e o conflito gerador.'),
('6º ano','LP','prova-parana','ESTADUAL','H 02 (D019_P)','H02','D019_P','Reconhecer formas de tratar uma informação na comparação de textos que tratam do mesmo tema.'),
('6º ano','LP','prova-parana','ESTADUAL','H 11 (D038_P)','H11','D038_P','Distinguir um fato da opinião.'),
('6º ano','LP','prova-parana','ESTADUAL','H 06 (D024_P)','H06','D024_P','Reconhecer efeito de humor ou de ironia em um texto.'),
('6º ano','LP','prova-parana','ESTADUAL','H 12 (D039_P)','H12','D039_P','Reconhecer o sentido das relações lógico-discursivas em um texto.'),
('6º ano','LP','prova-parana','ESTADUAL','H 01 (D016_P)','H01','D016_P','Identificar a finalidade de textos de diferentes gêneros.'),
('9º ano','LP','prova-parana','ESTADUAL','H 02 (D021_P)','H02','D021_P','Localizar informação explícita.'),
('3º ano','LP','prova-parana','ESTADUAL','H 02 (D021_P)','H02','D021_P','Localizar informação explícita.'),
('9º ano','LP','prova-parana','ESTADUAL','H 05 (D027_P)','H05','D027_P','Distinguir ideias centrais de secundárias ou tópicos e subtópicos em um dado gênero textual.'),
('9º ano','LP','prova-parana','ESTADUAL','H 08 (D033_P)','H08','D033_P','Reconhecer posições distintas relativas ao mesmo fato ou mesmo tema.'),
('9º ano','LP','mais','ESTADUAL','H 19 (D11)','H19','D11','Estabelecer relação causa/consequência entre partes e elementos do texto.'),
('9º ano','LP','mais','ESTADUAL','H 12 (D21)','H12','D21','Reconhecer posições distintas entre duas ou mais opiniões relativas ao mesmo fato ou ao mesmo tema.'),
('9º ano','LP','mais','ESTADUAL','H 21 (D13)','H21','D13','Identificar as marcas linguísticas que evidenciam o locutor e o interlocutor de um texto.'),
('9º ano','LP','mais','ESTADUAL','H 14 (D14)','H14','D14','Distinguir um fato da opinião relativa a esse fato.'),
('9º ano','LP','mais','ESTADUAL','H 17 (D08)','H17','D08','Estabelecer relação entre a tese e os argumentos oferecidos para sustentá-la.'),
('9º ano','LP','mais','ESTADUAL','H 11 (D07)','H11','D07','Identificar a tese de um texto.'),
('9º ano','LP','mais','ESTADUAL','H 20 (D19)','H20','D19','Reconhecer o efeito de sentido decorrente da exploração de recursos ortográficos e/ou morfossintáticos.'),
('9º ano','LP','mais','ESTADUAL','H 01 (D12)','H01','D12','Identificar a finalidade de textos de diferentes gêneros.'),
('9º ano','LP','mais','ESTADUAL','H 16 (D18)','H16','D18','Reconhecer o efeito de sentido decorrente da escolha de uma determinada palavra ou expressão.'),
('3º ano','LP','mais','ESTADUAL','H 05 (H05_LP)','H05','H05_LP','Distinguir um fato da opinião relativa a esse fato.'),
('3º ano','LP','mais','ESTADUAL','H 12 (H12_LP)','H12','H12_LP','Estabelecer relação entre a tese e os argumentos oferecidos para sustentá-la.'),
('3º ano','LP','mais','ESTADUAL','H 11 (H11_LP)','H11','H11_LP','Identificar a tese de um texto.'),
('3º ano','LP','mais','ESTADUAL','H 19 (H20_LP)','H19','H20_LP','Reconhecer o efeito de sentido decorrente da exploração de recursos ortográficos e/ou morfossintáticos.'),
('3º ano','LP','mais','ESTADUAL','H 07 (H07_LP)','H07','H07_LP','Identificar a finalidade de textos de diferentes gêneros.'),
('3º ano','LP','mais','ESTADUAL','H 18 (H19_LP)','H18','H19_LP','Reconhecer o efeito de sentido decorrente da escolha de uma determinada palavra ou expressão.'),
('1º ano','MT','parceiro','ESTADUAL','H 12 (D063_M)','H12','D063_M','Utilizar o Teorema de Tales na resolução de problema.'),
('2º ano','MT','parceiro','ESTADUAL','H 08 (D063_M)','H08','D063_M','Utilizar o Teorema de Tales na resolução de problema.'),
('6º ano','MT','parceiro','ESTADUAL','H 08 (D020_M)','H08','D020_M','Corresponder figuras tridimensionais às suas planificações.'),
('7º ano','MT','parceiro','ESTADUAL','H 02 (D020_M)','H02','D020_M','Corresponder figuras tridimensionais às suas planificações.'),
('8º ano','MT','parceiro','ESTADUAL','H 01 (D020_M)','H01','D020_M','Corresponder figuras tridimensionais às suas planificações.'),
('9º ano','MT','parceiro','ESTADUAL','H 01 (D020_M)','H01','D020_M','Corresponder figuras tridimensionais às suas planificações.'),
('6º ano','MT','parceiro','ESTADUAL','H 13 (D030_M)','H13','D030_M','Utilizar conversão entre unidades de medida, na resolução de problema.'),
('7º ano','MT','parceiro','ESTADUAL','H 08 (D030_M)','H08','D030_M','Utilizar conversão entre unidades de medida, na resolução de problema.'),
('8º ano','MT','parceiro','ESTADUAL','H 06 (D030_M)','H06','D030_M','Utilizar conversão entre unidades de medida, na resolução de problema.'),
('9º ano','MT','parceiro','ESTADUAL','H 05 (D030_M)','H05','D030_M','Utilizar conversão entre unidades de medida, na resolução de problema.'),
('7º ano','MT','parceiro','ESTADUAL','H 13 (D043_M)','H13','D043_M','Utilizar perímetro de figuras bidimensionais na resolução de problema.'),
('6º ano','MT','parceiro','ESTADUAL','H 12 (D029_M)','H12','D029_M','Reconhecer fração como representação associada a diferentes significados.'),
('7º ano','MT','parceiro','ESTADUAL','H 07 (D029_M)','H07','D029_M','Reconhecer fração como representação associada a diferentes significados.'),
('7º ano','MT','parceiro','ESTADUAL','H 15 (D079_M)','H15','D079_M','Utilizar números racionais, envolvendo diferentes significados da adição ou da subtração, na resolução de problemas.'),
('8º ano','MT','parceiro','ESTADUAL','H 14 (D079_M)','H14','D079_M','Utilizar números racionais, envolvendo diferentes significados da adição ou da subtração, na resolução de problemas.'),
('7º ano','MT','parceiro','ESTADUAL','H 04 (D022_M)','H04','D022_M','Utilizar números naturais, envolvendo diferentes significados da multiplicação ou da divisão, na resolução de problemas.'),
('8º ano','MT','parceiro','ESTADUAL','H 03 (D022_M)','H03','D022_M','Utilizar números naturais, envolvendo diferentes significados da multiplicação ou da divisão, na resolução de problemas.'),
('9º ano','MT','parceiro','ESTADUAL','H 03 (D022_M)','H03','D022_M','Utilizar números naturais, envolvendo diferentes significados da multiplicação ou da divisão, na resolução de problemas.'),
('7º ano','MT','parceiro','ESTADUAL','H 06 (D028_M)','H06','D028_M','Identificar frações equivalentes.'),
('8º ano','MT','parceiro','ESTADUAL','H 05 (D028_M)','H05','D028_M','Identificar frações equivalentes.'),
('7º ano','MT','parceiro','ESTADUAL','H 11 (D038_M)','H11','D038_M','Corresponder diferentes representações de um número racional.'),
('7º ano','MT','parceiro','ESTADUAL','H 14 (D044_M)','H14','D044_M','Utilizar porcentagem na resolução de problemas.'),
('9º ano','MT','parceiro','ESTADUAL','H 09 (D044_M)','H09','D044_M','Utilizar porcentagem na resolução de problemas.'),
('1º ano','MT','parceiro','ESTADUAL','H 05 (D044_M)','H05','D044_M','Utilizar porcentagem na resolução de problemas.'),
('6º ano','MT','parceiro','ESTADUAL','H 17 (D087_M)','H17','D087_M','Corresponder objetos em uma representação plana do espaço à sua localização descrita por meio de um par ordenado.'),
('7º ano','MT','parceiro','ESTADUAL','H 16 (D087_M)','H16','D087_M','Corresponder objetos em uma representação plana do espaço à sua localização descrita por meio de um par ordenado.'),
('8º ano','MT','parceiro','ESTADUAL','H 15 (D087_M)','H15','D087_M','Corresponder objetos em uma representação plana do espaço à sua localização descrita por meio de um par ordenado.'),
('9º ano','MT','parceiro','ESTADUAL','H 15 (D087_M)','H15','D087_M','Corresponder objetos em uma representação plana do espaço à sua localização descrita por meio de um par ordenado.'),
('8º ano','MT','parceiro','ESTADUAL','H 09 (D037_M)','H09','D037_M','Classificar triângulos por meio de suas propriedades.'),
('1º ano','MT','parceiro','ESTADUAL','H 04 (D037_M)','H04','D037_M','Classificar triângulos por meio de suas propriedades.'),
('2º ano','MT','parceiro','ESTADUAL','H 04 (D037_M)','H04','D037_M','Classificar triângulos por meio de suas propriedades.'),
('3º ano','MT','parceiro','ESTADUAL','H 03 (D037_M)','H03','D037_M','Classificar triângulos por meio de suas propriedades.'),
('7º ano','MT','parceiro','ESTADUAL','H 17 (D088_M)','H17','D088_M','Reconhecer ângulos como mudança de direção, ângulo de visão ou giro, identificando ângulos retos e não retos.'),
('8º ano','MT','parceiro','ESTADUAL','H 16 (D088_M)','H16','D088_M','Reconhecer ângulos como mudança de direção, ângulo de visão ou giro, identificando ângulos retos e não retos.'),
('7º ano','MT','parceiro','ESTADUAL','H 03 (D021_M)','H03','D021_M','Utilizar informações apresentadas em tabelas ou gráficos na resolução de problemas.'),
('8º ano','MT','parceiro','ESTADUAL','H 02 (D021_M)','H02','D021_M','Utilizar informações apresentadas em tabelas ou gráficos na resolução de problemas.'),
('9º ano','MT','parceiro','ESTADUAL','H 02 (D021_M)','H02','D021_M','Utilizar informações apresentadas em tabelas ou gráficos na resolução de problemas.'),
('6º ano','MT','parceiro','ESTADUAL','H 10 (D026_M)','H10','D026_M','Corresponder números racionais a pontos da reta numérica.'),
('6º ano','MT','parceiro','ESTADUAL','H 06 (D013_M)','H06','D013_M','Identificar números naturais segundo critérios de ordem.'),
('8º ano','MT','parceiro','ESTADUAL','H 17 (D089_M)','H17','D089_M','Identificar números inteiros segundo critérios de ordem.'),
('8º ano','MT','parceiro','ESTADUAL','H 18 (D090_M)','H18','D090_M','Executar a adição ou a subtração entre números inteiros.'),
('8º ano','MT','parceiro','ESTADUAL','H 12 (D050_M)','H12','D050_M','Utilizar números inteiros, envolvendo diferentes significados da multiplicação ou da divisão, na resolução de problemas.'),
('1º ano','MT','parceiro','ESTADUAL','H 15 (D090_M)','H15','D090_M','Executar a adição ou a subtração entre números inteiros.'),
('2º ano','MT','parceiro','ESTADUAL','H 17 (D090_M)','H17','D090_M','Executar a adição ou a subtração entre números inteiros.'),
('3º ano','MT','parceiro','ESTADUAL','H 10 (D090_M)','H10','D090_M','Executar a adição ou a subtração entre números inteiros.'),
('8º ano','MT','parceiro','ESTADUAL','H 19 (D091_M)','H19','D091_M','Identificar uma expressão algébrica que representa uma situação problema descrita textualmente.'),
('9º ano','MT','parceiro','ESTADUAL','H 16 (D091_M)','H16','D091_M','Identificar uma expressão algébrica que representa uma situação problema descrita textualmente.'),
('8º ano','MT','parceiro','ESTADUAL','H 08 (D035_M)','H08','D035_M','Utilizar proporcionalidade entre duas grandezas na resolução de problema.'),
('9º ano','MT','parceiro','ESTADUAL','H 08 (D035_M)','H08','D035_M','Utilizar proporcionalidade entre duas grandezas na resolução de problema.'),
('1º ano','MT','parceiro','ESTADUAL','H 03 (D035_M)','H03','D035_M','Utilizar proporcionalidade entre duas grandezas na resolução de problema.'),
('2º ano','MT','parceiro','ESTADUAL','H 03 (D035_M)','H03','D035_M','Utilizar proporcionalidade entre duas grandezas na resolução de problema.'),
('8º ano','MT','parceiro','ESTADUAL','H 11 (D048_M)','H11','D048_M','Utilizar equação polinomial de 1º grau na resolução de problema.'),
('1º ano','MT','parceiro','ESTADUAL','H 06 (D048_M)','H06','D048_M','Utilizar equação polinomial de 1º grau na resolução de problema.'),
('2º ano','MT','parceiro','ESTADUAL','H 05 (D048_M)','H05','D048_M','Utilizar equação polinomial de 1º grau na resolução de problema.'),
('3º ano','MT','parceiro','ESTADUAL','H 04 (D048_M)','H04','D048_M','Utilizar equação polinomial de 1º grau na resolução de problema.'),
('8º ano','MT','parceiro','ESTADUAL','H 20 (D092_M)','H20','D092_M','Reconhecer, no plano cartesiano, o simétrico de figuras em relação a um dos eixos ou à origem.'),
('8º ano','MT','parceiro','ESTADUAL','H 21 (D093_M)','H21','D093_M','Utilizar o cálculo da medida do ângulo interno de um polígono regular na resolução de problemas.'),
('9º ano','MT','parceiro','ESTADUAL','H 17 (D093_M)','H17','D093_M','Utilizar o cálculo da medida do ângulo interno de um polígono regular na resolução de problemas.'),
('3º ano','MT','parceiro','ESTADUAL','H 07 (D075_M)','H07','D075_M','Utilizar a medida da área total e/ou lateral de um sólido na resolução de problema.'),
('9º ano','MT','parceiro','ESTADUAL','H 06 (D033_M)','H06','D033_M','Utilizar o princípio multiplicativo de contagem na resolução de problema.'),
('1º ano','MT','parceiro','ESTADUAL','H 19 (D105_M)','H19','D105_M','Utilizar equação polinomial de 2º grau na resolução de problema.'),
('7º ano','MT','parceiro','ESTADUAL','H 05 (D025_M)','H05','D025_M','Utilizar área de figuras bidimensionais na resolução de problema.'),
('8º ano','MT','parceiro','ESTADUAL','H 04 (D025_M)','H04','D025_M','Utilizar área de figuras bidimensionais na resolução de problema.'),
('9º ano','MT','parceiro','ESTADUAL','H 04 (D025_M)','H04','D025_M','Utilizar área de figuras bidimensionais na resolução de problema.'),
('1º ano','MT','parceiro','ESTADUAL','H 01 (D025_M)','H01','D025_M','Utilizar área de figuras bidimensionais na resolução de problema.'),
('2º ano','MT','parceiro','ESTADUAL','H 01 (D025_M)','H01','D025_M','Utilizar área de figuras bidimensionais na resolução de problema.'),
('3º ano','MT','parceiro','ESTADUAL','H 01 (D025_M)','H01','D025_M','Utilizar área de figuras bidimensionais na resolução de problema.'),
('8º ano','MT','parceiro','ESTADUAL','H 22 (D107_M)','H22','D107_M','Utilizar volume/capacidade de sólidos geométricos na resolução de problema.'),
('9º ano','MT','parceiro','ESTADUAL','H 21 (D107_M)','H21','D107_M','Utilizar volume/capacidade de sólidos geométricos na resolução de problema.'),
('1º ano','MT','parceiro','ESTADUAL','H 20 (D107_M)','H20','D107_M','Utilizar volume/capacidade de sólidos geométricos na resolução de problema.'),
('2º ano','MT','parceiro','ESTADUAL','H 22 (D107_M)','H22','D107_M','Utilizar volume/capacidade de sólidos geométricos na resolução de problema.'),
('3º ano','MT','parceiro','ESTADUAL','H 12 (D107_M)','H12','D107_M','Utilizar volume/capacidade de sólidos geométricos na resolução de problema.'),
('6º ano','MT','parceiro','ESTADUAL','H 16 (D034_M)','H16','D034_M','Utilizar probabilidade na resolução de problema.'),
('8º ano','MT','parceiro','ESTADUAL','H 07 (D034_M)','H07','D034_M','Utilizar probabilidade na resolução de problema.'),
('9º ano','MT','parceiro','ESTADUAL','H 07 (D034_M)','H07','D034_M','Utilizar probabilidade na resolução de problema.'),
('1º ano','MT','parceiro','ESTADUAL','H 02 (D034_M)','H02','D034_M','Utilizar probabilidade na resolução de problema.'),
('2º ano','MT','parceiro','ESTADUAL','H 02 (D034_M)','H02','D034_M','Utilizar probabilidade na resolução de problema.'),
('3º ano','MT','parceiro','ESTADUAL','H 02 (D034_M)','H02','D034_M','Utilizar probabilidade na resolução de problema.'),
('8º ano','MT','parceiro','ESTADUAL','H 13 (D056_M)','H13','D056_M','Utilizar medidas de tendência central na resolução de problema.'),
('9º ano','MT','parceiro','ESTADUAL','H 11 (D056_M)','H11','D056_M','Utilizar medidas de tendência central na resolução de problema.'),
('2º ano','MT','parceiro','ESTADUAL','H 06 (D056_M)','H06','D056_M','Utilizar medidas de tendência central na resolução de problema.'),
('3º ano','MT','parceiro','ESTADUAL','H 05 (D056_M)','H05','D056_M','Utilizar medidas de tendência central na resolução de problema.'),
('1º ano','MT','parceiro','ESTADUAL','H 07 (D053_M)','H07','D053_M','Executar cálculos com números reais.'),
('2º ano','MT','parceiro','ESTADUAL','H 10 (D066_M)','H10','D066_M','Analisar regiões de crescimento/decrescimento, domínios de validade ou zeros de funções reais representadas graficamente.'),
('3º ano','MT','parceiro','ESTADUAL','H 06 (D066_M)','H06','D066_M','Analisar regiões de crescimento/decrescimento, domínios de validade ou zeros de funções reais representadas graficamente.'),
('1º ano','MT','parceiro','ESTADUAL','H 18 (D100_M)','H18','D100_M','Fatorar e/ou simplificar expressões algébricas, com base nos produtos notáveis.'),
('2º ano','MT','parceiro','ESTADUAL','H 18 (D100_M)','H18','D100_M','Fatorar e/ou simplificar expressões algébricas, com base nos produtos notáveis.'),
('3º ano','MT','parceiro','ESTADUAL','H 14 (D109_M)','H14','D109_M','Relacionar as raízes de um polinômio com sua decomposição em fatores do 1º grau.'),
('8º ano','MT','parceiro','ESTADUAL','H 10 (D047_M)','H10','D047_M','Utilizar as relações entre as medidas dos ângulos formados entre uma reta transversal e um feixe de retas paralelas para se obter a medida de um ângulo especificado.'),
('1º ano','MT','parceiro','ESTADUAL','H 09 (D060_M)','H09','D060_M','Identificar triângulos semelhantes.'),
('2º ano','MT','parceiro','ESTADUAL','H 07 (D060_M)','H07','D060_M','Identificar triângulos semelhantes.'),
('1º ano','MT','parceiro','ESTADUAL','H 13 (D064_M)','H13','D064_M','Utilizar relações métricas de um triângulo retângulo na resolução de problema.'),
('2º ano','MT','parceiro','ESTADUAL','H 09 (D064_M)','H09','D064_M','Utilizar relações métricas de um triângulo retângulo na resolução de problema.'),
('3º ano','MT','parceiro','ESTADUAL','H 18 (D113_M)','H18','D113_M','Resolver problemas que envolvam razões trigonométricas no triângulo retângulo.'),
('9º ano','MT','parceiro','ESTADUAL','H 12 (D057_M)','H12','D057_M','Utilizar o cálculo do valor numérico de expressões algébricas na resolução de problemas.'),
('2º ano','MT','parceiro','ESTADUAL','H 19 (D101_M)','H19','D101_M','Identificar a representação algébrica ou gráfica de uma função exponencial.'),
('2º ano','MT','parceiro','ESTADUAL','H 15 (D076_M)','H15','D076_M','Utilizar função exponencial na resolução de problemas.'),
('3º ano','MT','parceiro','ESTADUAL','H 11 (D101_M)','H11','D101_M','Identificar a representação algébrica ou gráfica de uma função exponencial.'),
('3º ano','MT','parceiro','ESTADUAL','H 08 (D076_M)','H08','D076_M','Utilizar função exponencial na resolução de problemas.'),
('3º ano','MT','parceiro','ESTADUAL','H 15 (D110_M)','H15','D110_M','Reconhecer a representação gráfica das funções trigonométricas (seno, cosseno e tangente).'),
('2º ano','MT','parceiro','ESTADUAL','H 11 (D067_M)','H11','D067_M','Corresponder a representação algébrica e gráfica de uma função polinomial de 1º grau.'),
('9º ano','MT','parceiro','ESTADUAL','H 13 (D068_M)','H13','D068_M','Corresponder um sistema de equações polinomiais de 1º grau à uma situação problema descrita textualmente.'),
('2º ano','MT','parceiro','ESTADUAL','H 13 (D070_M)','H13','D070_M','Utilizar função polinomial de 1º grau na resolução de problemas.'),
('2º ano','MT','parceiro','ESTADUAL','H 16 (D077_M)','H16','D077_M','Utilizar função polinomial de 2º grau na resolução de problemas.'),
('3º ano','MT','parceiro','ESTADUAL','H 09 (D078_M)','H09','D078_M','Utilizar propriedades de progressões aritméticas ou geométricas na resolução de problemas.'),
('9º ano','MT','prova-parana','ESTADUAL','H 01 (D020_M)','H01','D020_M','Corresponder figuras tridimensionais às suas planificações.'),
('9º ano','MT','prova-parana','ESTADUAL','H 05 (D030_M)','H05','D030_M','Utilizar conversão entre unidades de medida, na resolução de problema.'),
('9º ano','MT','prova-parana','ESTADUAL','H 12 (D043_M)','H12','D043_M','Utilizar perímetro de figuras bidimensionais na resolução de problema.'),
('3º ano','MT','prova-parana','ESTADUAL','H 07 (D043_M)','H07','D043_M','Utilizar perímetro de figuras bidimensionais na resolução de problema.'),
('9º ano','MT','prova-parana','ESTADUAL','H 04 (D028_M)','H04','D028_M','Identificar frações equivalentes.'),
('9º ano','MT','prova-parana','ESTADUAL','H 10 (D038_M)','H10','D038_M','Corresponder diferentes representações de um número racional.'),
('9º ano','MT','prova-parana','ESTADUAL','H 13 (D044_M)','H13','D044_M','Utilizar porcentagem na resolução de problemas.'),
('3º ano','MT','prova-parana','ESTADUAL','H 05 (D039_M)','H05','D039_M','Corresponder pontos do plano a pares ordenados em um sistema de coordenadas cartesianas.'),
('9º ano','MT','prova-parana','ESTADUAL','H 09 (D037_M)','H09','D037_M','Classificar triângulos por meio de suas propriedades.'),
('9º ano','MT','prova-parana','ESTADUAL','H 08 (D036_M)','H08','D036_M','Classificar quadriláteros por meio de suas propriedades.'),
('9º ano','MT','prova-parana','ESTADUAL','H 02 (D021_M)','H02','D021_M','Utilizar informações apresentadas em tabelas ou gráficos na resolução de problemas.'),
('3º ano','MT','prova-parana','ESTADUAL','H 01 (D021_M)','H01','D021_M','Utilizar informações apresentadas em tabelas ou gráficos na resolução de problemas.'),
('9º ano','MT','prova-parana','ESTADUAL','H 19 (D128_M)','H19','D128_M','Utilizar números racionais, envolvendo diferentes significados das operações, na resolução de problemas.'),
('9º ano','MT','prova-parana','ESTADUAL','H 14 (D046_M)','H14','D046_M','Identificar a expressão algébrica que expressa uma regularidade observada em sequência de números ou figuras (padrões).'),
('9º ano','MT','prova-parana','ESTADUAL','H 07 (D035_M)','H07','D035_M','Utilizar proporcionalidade entre duas grandezas na resolução de problema.'),
('3º ano','MT','prova-parana','ESTADUAL','H 04 (D035_M)','H04','D035_M','Utilizar proporcionalidade entre duas grandezas na resolução de problema.'),
('9º ano','MT','prova-parana','ESTADUAL','H 20 (D129_M)','H20','D129_M','Identificar uma equação ou inequação do 1º grau que expressa um problema.'),
('3º ano','MT','prova-parana','ESTADUAL','H 12 (D075_M)','H12','D075_M','Utilizar a medida da área total e/ou lateral de um sólido na resolução de problema.'),
('9º ano','MT','prova-parana','ESTADUAL','H 06 (D033_M)','H06','D033_M','Utilizar o princípio multiplicativo de contagem na resolução de problema.'),
('3º ano','MT','prova-parana','ESTADUAL','H 02 (D033_M)','H02','D033_M','Utilizar o princípio multiplicativo de contagem na resolução de problema.'),
('9º ano','MT','prova-parana','ESTADUAL','H 16 (D057_M)','H16','D057_M','Utilizar o cálculo do valor numérico de expressões algébricas na resolução de problemas.'),
('9º ano','MT','prova-parana','ESTADUAL','H 18 (D105_M)','H18','D105_M','Utilizar equação polinomial de 2º grau na resolução de problema.'),
('3º ano','MT','prova-parana','ESTADUAL','H 16 (D105_M)','H16','D105_M','Utilizar equação polinomial de 2º grau na resolução de problema.'),
('9º ano','MT','prova-parana','ESTADUAL','H 03 (D025_M)','H03','D025_M','Utilizar área de figuras bidimensionais na resolução de problema.'),
('3º ano','MT','prova-parana','ESTADUAL','H 03 (D034_M)','H03','D034_M','Utilizar probabilidade na resolução de problema.'),
('9º ano','MT','prova-parana','ESTADUAL','H 15 (D053_M)','H15','D053_M','Executar cálculos com números reais.'),
('3º ano','MT','prova-parana','ESTADUAL','H 09 (D066_M)','H09','D066_M','Analisar regiões de crescimento/decrescimento, domínios de validade ou zeros de funções reais representadas graficamente.'),
('9º ano','MT','prova-parana','ESTADUAL','H 17 (D064_M)','H17','D064_M','Utilizar relações métricas de um triângulo retângulo na resolução de problema.'),
('3º ano','MT','prova-parana','ESTADUAL','H 18 (D113_M)','H18','D113_M','Resolver problemas que envolvam razões trigonométricas no triângulo retângulo.'),
('3º ano','MT','prova-parana','ESTADUAL','H 08 (D064_M)','H08','D064_M','Utilizar relações métricas de um triângulo retângulo na resolução de problema.'),
('9º ano','MT','prova-parana','ESTADUAL','H 11 (D042_M)','H11','D042_M','Utilizar o cálculo de volumes/capacidade de prismas retos e de cilindros na resolução de problema.'),
('3º ano','MT','prova-parana','ESTADUAL','H 06 (D042_M)','H06','D042_M','Utilizar o cálculo de volumes/capacidade de prismas retos e de cilindros na resolução de problema.'),
('3º ano','MT','prova-parana','ESTADUAL','H 13 (D076_M)','H13','D076_M','Utilizar função exponencial na resolução de problemas.'),
('3º ano','MT','prova-parana','ESTADUAL','H 17 (D110_M)','H17','D110_M','Reconhecer a representação gráfica das funções trigonométricas (seno, cosseno e tangente).'),
('3º ano','MT','prova-parana','ESTADUAL','H 10 (D070_M)','H10','D070_M','Utilizar função polinomial de 1º grau na resolução de problemas.'),
('3º ano','MT','prova-parana','ESTADUAL','H 11 (D074_M)','H11','D074_M','Reconhecer a representação algébrica de uma função polinomial de 2º grau a partir dos dados apresentados em uma tabela.'),
('3º ano','MT','prova-parana','ESTADUAL','H 14 (D077_M)','H14','D077_M','Utilizar função polinomial de 2º grau na resolução de problemas.'),
('3º ano','MT','prova-parana','ESTADUAL','H 15 (D078_M)','H15','D078_M','Utilizar propriedades de progressões aritméticas ou geométricas na resolução de problemas.'),
('6º ano','MT','prova-parana','ESTADUAL','H 11 (D020_M)','H11','D020_M','Corresponder figuras tridimensionais às suas planificações.'),
('6º ano','MT','prova-parana','ESTADUAL','H 16 (D030_M)','H16','D030_M','Utilizar conversão entre unidades de medida, na resolução de problema.'),
('6º ano','MT','prova-parana','ESTADUAL','H 19 (D043_M)','H19','D043_M','Utilizar perímetro de figuras bidimensionais na resolução de problema.'),
('6º ano','MT','prova-parana','ESTADUAL','H 15 (D029_M)','H15','D029_M','Reconhecer fração como representação associada a diferentes significados.'),
('6º ano','MT','prova-parana','ESTADUAL','H 21 (D079_M)','H21','D079_M','Utilizar números racionais, envolvendo diferentes significados da adição ou da subtração, na resolução de problemas.'),
('6º ano','MT','prova-parana','ESTADUAL','H 05 (D005_M)','H05','D005_M','Utilizar números naturais, envolvendo diferentes significados da adição ou da subtração, na resolução de problemas.'),
('6º ano','MT','prova-parana','ESTADUAL','H 12 (D022_M)','H12','D022_M','Utilizar números naturais, envolvendo diferentes significados da multiplicação ou da divisão, na resolução de problemas.'),
('6º ano','MT','prova-parana','ESTADUAL','H 17 (D038_M)','H17','D038_M','Corresponder diferentes representações de um número racional.'),
('6º ano','MT','prova-parana','ESTADUAL','H 20 (D044_M)','H20','D044_M','Utilizar porcentagem na resolução de problemas.'),
('6º ano','MT','prova-parana','ESTADUAL','H 10 (D016_M)','H10','D016_M','Corresponder números naturais a pontos da reta numérica.'),
('6º ano','MT','prova-parana','ESTADUAL','H 14 (D026_M)','H14','D026_M','Corresponder números racionais a pontos da reta numérica.'),
('6º ano','MT','prova-parana','ESTADUAL','H 13 (D025_M)','H13','D025_M','Utilizar área de figuras bidimensionais na resolução de problema.'),
('3º ano','MT','prova-parana','ESTADUAL','H 01 (D020_M)','H01','D020_M','Corresponder figuras tridimensionais às suas planificações.'),
('9º ano','MT','prova-parana','ESTADUAL','H 06 (D029_M)','H06','D029_M','Reconhecer fração como representação associada a diferentes significados.'),
('9º ano','MT','prova-parana','ESTADUAL','H 04 (D026_M)','H04','D026_M','Corresponder números racionais a pontos da reta numérica.'),
('3º ano','MT','prova-parana','ESTADUAL','H 09 (D044_M)','H09','D044_M','Utilizar porcentagem na resolução de problemas.'),
('9º ano','MT','prova-parana','ESTADUAL','H 11 (D039_M)','H11','D039_M','Corresponder pontos do plano a pares ordenados em um sistema de coordenadas cartesianas.'),
('9º ano','MT','prova-parana','ESTADUAL','H 14 (D045_M)','H14','D045_M','Corresponder números inteiros a pontos da reta numérica.'),
('9º ano','MT','prova-parana','ESTADUAL','H 20 (D117_M)','H20','D117_M','Efetuar cálculos simples com valores aproximados de radicais.'),
('3º ano','MT','prova-parana','ESTADUAL','H 20 (D109_M)','H20','D109_M','Relacionar as raízes de um polinômio com sua decomposição em fatores do 1º grau.'),
('3º ano','MT','prova-parana','ESTADUAL','H 18 (D101_M)','H18','D101_M','Identificar a representação algébrica ou gráfica de uma função exponencial.'),
('3º ano','MT','prova-parana','ESTADUAL','H 12 (D067_M)','H12','D067_M','Corresponder a representação algébrica e gráfica de uma função polinomial de 1º grau.'),
('9º ano','MT','prova-parana','ESTADUAL','H 18 (D068_M)','H18','D068_M','Corresponder um sistema de equações polinomiais de 1º grau à uma situação problema descrita textualmente.'),
('9º ano','MT','mais','ESTADUAL','H 23 (D23)','H23','D23','Identificar frações equivalentes.'),
('9º ano','MT','mais','ESTADUAL','H 06 (D06)','H06','D06','Reconhecer ângulos como mudança de direção ou giros, identificando ângulos retos e não-retos.'),
('9º ano','MT','mais','ESTADUAL','H 32 (D32)','H32','D32','Identificar a expressão algébrica que expressa uma regularidade observada em sequências de números ou figuras (padrões).'),
('9º ano','MT','mais','ESTADUAL','H 34 (D34)','H34','D34','Identificar um sistema de equações do 1º grau que expressa um problema.'),
('9º ano','MT','mais','ESTADUAL','H 33 (D33)','H33','D33','Identificar uma equação ou inequação do 1º grau que expressa um problema.'),
('9º ano','MT','mais','ESTADUAL','H 27 (D27)','H27','D27','Efetuar cálculos simples com valores aproximados de radicais.'),
('9º ano','MT','mais','ESTADUAL','H 10 (D10)','H10','D10','Utilizar relações métricas do triângulo retângulo para resolver problemas significativos.'),
('3º ano','MT','mais','ESTADUAL','H 19 (H34_MT)','H19','H34_MT','Identificar a representação algébrica e/ou gráfica de uma função exponencial.'),
('3º ano','CH','mais','ESTADUAL','H 06 (H03_HI)','H06','H03_HI','Analisar a atuação dos movimentos sociais urbanos e rurais que contribuíram para mudanças ou rupturas em processos de disputa pelo poder.'),
('3º ano','CH','mais','ESTADUAL','H 07 (H04_GE)','H07','H04_GE','Analisar fatores que explicam o impacto das novas tecnologias no processo de territorialização da produção.'),
('3º ano','CH','mais','ESTADUAL','H 04 (H02_HI)','H04','H02_HI','Comparar o significado histórico das organizações políticas - democráticas e ou autoritárias - em seus contextos socioeconômicos em escala local, regional ou mundial.'),
('3º ano','CH','mais','ESTADUAL','H 05 (H03_GE)','H05','H03_GE','Comparar o significado histórico-geográfico das organizações políticas e socioeconômicas em escala local, regional ou mundial.'),
('3º ano','CH','mais','ESTADUAL','H 13 (H07_HI)','H13','H07_HI','Identificar em fontes diversas processos históricos de ocupação territorial, as relações da vida humana com a paisagem e suas práticas culturais em diferentes temporalidades.'),
('3º ano','CH','mais','ESTADUAL','H 02 (H01_HI)','H02','H01_HI','Identificar os significados histórico-geográficos das relações de poder entre as nações, a formação dos Estados nacionais e o processo de modernização.'),
('3º ano','CH','mais','ESTADUAL','H 03 (H02_GE)','H03','H02_GE','Identificar os significados histórico-geográficos das relações de poder entre as nações.'),
('3º ano','CH','mais','ESTADUAL','H 01 (H01_GE)','H01','H01_GE','Interpretar diferentes representações gráficas e cartográficas dos espaços geográficos.'),
('3º ano','CH','mais','ESTADUAL','H 11 (H06_GE)','H11','H06_GE','Reconhecer a função dos recursos naturais na produção do espaço geográfico, relacionando-os com as mudanças provocadas pelas ações humanas.'),
('3º ano','CH','mais','ESTADUAL','H 10 (H05_HI)','H10','H05_HI','Reconhecer as transformações técnicas e tecnológicas nas relações de trabalho, nos modos de vida e nas várias formas de uso e apropriação dos espaços rural e urbano.'),
('3º ano','CH','mais','ESTADUAL','H 09 (H05_GE)','H09','H05_GE','Reconhecer as transformações técnicas e tecnológicas que determinam as várias formas de uso e apropriação dos espaços rural e urbano.'),
('3º ano','CH','mais','ESTADUAL','H 12 (H06_HI)','H12','H06_HI','Relacionar cidadania e democracia na organização das sociedades.'),
('3º ano','CN','mais','ESTADUAL','H 10 (H04_BI)','H10','H04_BI','Analisar perturbações ambientais, identificando fontes, transporte e(ou) destino dos poluentes ou prevendo efeitos em sistemas naturais, produtivos ou sociais.'),
('3º ano','CN','mais','ESTADUAL','H 22 (H11_BI)','H22','H11_BI','Associar características adaptativas dos organismos com seu modo de vida ou com seus limites de distribuição em diferentes ambientes, em especial em ambientes brasileiros.'),
('3º ano','CN','mais','ESTADUAL','H 16 (H06_BI)','H16','H06_BI','Avaliar impactos em ambientes naturais decorrentes de atividades sociais ou econômicas, considerando interesses contraditórios.'),
('3º ano','CN','mais','ESTADUAL','H 17 (H06_FI)','H17','H06_FI','Avaliar possibilidades de geração, uso ou transformação de energia em ambientes específicos, considerando implicações éticas, ambientais, sociais e/ou econômicas.'),
('3º ano','CN','mais','ESTADUAL','H 23 (H13_BI)','H23','H13_BI','Avaliar propostas de alcance individual ou coletivo, identificando aquelas que visam à preservação e a implementação da saúde individual, coletiva ou do ambiente.'),
('3º ano','CN','mais','ESTADUAL','H 01 (H01_BI)','H01','H01_BI','Avaliar propostas de intervenção no ambiente, considerando a qualidade da vida humana ou medidas de conservação, recuperação ou utilização sustentável da biodiversidade.'),
('3º ano','CN','mais','ESTADUAL','H 11 (H04_FI)','H11','H04_FI','Caracterizar causas ou efeitos dos movimentos de partículas, substâncias, objetos ou corpos celestes.'),
('3º ano','CN','mais','ESTADUAL','H 06 (H02_QU)','H06','H02_QU','Compreender a importância dos ciclos biogeoquímicos ou do fluxo de energia para a vida, ou da ação de agentes ou fenômenos que podem causar alterações nesses processos.'),
('3º ano','CN','mais','ESTADUAL','H 07 (H03_BI)','H07','H03_BI','Compreender a importância dos ciclos biogeoquímicos ou do fluxo de energia para a vida, ou da ação de agentes ou fenômenos que podem causar alterações nesses processos.'),
('3º ano','CN','mais','ESTADUAL','H 21 (H10_BI)','H21','H10_BI','Compreender o papel da evolução na produção de padrões, processos biológicos ou na organização taxonômica dos seres vivos.'),
('3º ano','CN','mais','ESTADUAL','H 05 (H02_FI)','H05','H02_FI','Dimensionar circuitos ou dispositivos elétricos de uso cotidiano.'),
('3º ano','CN','mais','ESTADUAL','H 03 (H01_QU)','H03','H01_QU','Identificar etapas em processos de obtenção, transformação, utilização ou reciclagem de recursos naturais, energéticos ou matérias-primas, considerando processos biológicos, químicos ou físicos neles envolvidos.'),
('3º ano','CN','mais','ESTADUAL','H 04 (H02_BI)','H04','H02_BI','Identificar etapas em processos de obtenção, transformação, utilização ou reciclagem de recursos naturais, energéticos ou matérias-primas, considerando processos biológicos, químicos ou físicos neles envolvidos.'),
('3º ano','CN','mais','ESTADUAL','H 19 (H08_BI)','H19','H08_BI','Identificar padrões em fenômenos e processos vitais dos organismos, como manutenção do equilíbrio interno, defesa, relações com o ambiente, sexualidade, entre outros.'),
('3º ano','CN','mais','ESTADUAL','H 20 (H09_BI)','H20','H09_BI','Interpretar modelos e experimentos para explicar fenômenos ou processos biológicos em qualquer nível de organização dos sistemas biológicos.'),
('3º ano','CN','mais','ESTADUAL','H 13 (H05_BI)','H13','H05_BI','Reconhecer benefícios, limitações e aspectos éticos da biotecnologia, considerando estruturas e processos biológicos envolvidos em produtos biotecnológicos.'),
('3º ano','CN','mais','ESTADUAL','H 02 (H01_FI)','H02','H01_FI','Reconhecer características ou propriedades de fenômenos ondulatórios ou oscilatórios, relacionando-os a seus usos em diferentes contextos.'),
('3º ano','CN','mais','ESTADUAL','H 18 (H07_BI)','H18','H07_BI','Reconhecer mecanismos de transmissão da vida, prevendo ou explicando a manifestação de características dos seres vivos.'),
('3º ano','CN','mais','ESTADUAL','H 08 (H03_FI)','H08','H03_FI','Relacionar informações apresentadas em diferentes formas de linguagem e representação usadas nas ciências físicas, químicas ou biológicas, como texto discursivo, gráficos, tabelas, relações matemáticas ou linguagem simbólica.'),
('3º ano','CN','mais','ESTADUAL','H 09 (H03_QU)','H09','H03_QU','Relacionar informações apresentadas em diferentes formas de linguagem e representação usadas nas ciências físicas, químicas ou biológicas, como texto discursivo, gráficos, tabelas, relações matemáticas ou linguagem simbólica.'),
('3º ano','CN','mais','ESTADUAL','H 12 (H04_QU)','H12','H04_QU','Relacionar propriedades físicas, químicas ou biológicas de produtos, sistemas ou procedimentos tecnológicos às finalidades a que se destinam.'),
('3º ano','CN','mais','ESTADUAL','H 15 (H05_QU)','H15','H05_QU','Utilizar códigos e nomenclatura da química para caracterizar materiais, substâncias ou transformações químicas.'),
('3º ano','CN','mais','ESTADUAL','H 14 (H05_FI)','H14','H05_FI','Utilizar leis físicas e (ou) químicas para interpretar processos naturais ou tecnológicos inseridos no contexto da termodinâmica e(ou) do eletromagnetismo.'),
('6º ano','LP','parceiro','ESTADUAL','H 11 (D044_P)','H11','D044_P','Identificar marcas linguísticas em um texto.'),
('7º ano','LP','parceiro','ESTADUAL','H 13 (D044_P)','H13','D044_P','Identificar marcas linguísticas em um texto.'),
('9º ano','LP','parceiro','ESTADUAL','H 14 (D044_P)','H14','D044_P','Identificar marcas linguísticas em um texto.'),
('1º ano','LP','parceiro','ESTADUAL','H 11 (D044_P)','H11','D044_P','Identificar marcas linguísticas em um texto.'),
('2º ano','LP','parceiro','ESTADUAL','H 12 (D044_P)','H12','D044_P','Identificar marcas linguísticas em um texto.'),
('3º ano','LP','parceiro','ESTADUAL','H 15 (D044_P)','H15','D044_P','Identificar marcas linguísticas em um texto.'),
('6º ano','LP','parceiro','ESTADUAL','H 10 (D039_P)','H10','D039_P','Reconhecer o sentido das relações lógico-discursivas em um texto.'),
('1º ano','LP','parceiro','ESTADUAL','H 09 (D039_P)','H09','D039_P','Reconhecer o sentido das relações lógico-discursivas em um texto.'),
('6º ano','LP','prova-parana','ESTADUAL','H 13 (D057_P)','H13','D057_P','Interpretar textos que articulam elementos verbais e não verbais.'),
('9º ano','LP','mais','ESTADUAL','H 08 (D09)','H08','D09','Diferenciar as partes principais das secundárias em um texto.'),
('9º ano','LP','mais','ESTADUAL','H 13 (D02)','H13','D02','Estabelecer relações entre partes de um texto, identificando repetições ou substituições que contribuem para a continuidade de um texto.'),
('9º ano','LP','mais','ESTADUAL','H 15 (D15)','H15','D15','Estabelecer relações lógico-discursivas presentes no texto, marcadas por conjunções, advérbios, etc.'),
('9º ano','LP','mais','ESTADUAL','H 06 (D16)','H06','D16','Identificar efeitos de ironia ou humor em textos variados.'),
('9º ano','LP','mais','ESTADUAL','H 10 (D10)','H10','D10','Identificar o conflito gerador do enredo e os elementos que constroem a narrativa.'),
('9º ano','LP','mais','ESTADUAL','H 09 (D06)','H09','D06','Identificar o tema de um texto.'),
('9º ano','LP','mais','ESTADUAL','H 04 (D03)','H04','D03','Inferir o sentido de uma palavra ou expressão.'),
('9º ano','LP','mais','ESTADUAL','H 05 (D04)','H05','D04','Inferir uma informação implícita em um texto.'),
('9º ano','LP','mais','ESTADUAL','H 18 (D05)','H18','D05','Interpretar texto com auxílio de material gráfico diverso (propagandas, quadrinhos, foto, etc.).'),
('9º ano','LP','mais','ESTADUAL','H 03 (D01)','H03','D01','Localizar informações explícitas em um texto.'),
('9º ano','LP','mais','ESTADUAL','H 02 (D20)','H02','D20','Reconhecer diferentes formas de tratar uma informação na comparação de textos que tratam do mesmo tema, em função das condições em que ele foi produzido e daquelas em que será recebido.'),
('9º ano','LP','mais','ESTADUAL','H 07 (D17)','H07','D17','Reconhecer o efeito de sentido decorrente do uso da pontuação e de outras notações.'),
('3º ano','LP','mais','ESTADUAL','H 15 (H16_LP)','H15','H16_LP','Estabelecer relações lógico-discursivas presentes no texto, marcadas por conjunções, advérbios, etc.'),
('3º ano','LP','mais','ESTADUAL','H 16 (H17_LP)','H16','H17_LP','Identificar efeitos de ironia ou humor em textos variados.'),
('3º ano','LP','mais','ESTADUAL','H 14 (H14_LP)','H14','H14_LP','Identificar o conflito gerador do enredo e os elementos que constroem a narrativa.'),
('3º ano','LP','mais','ESTADUAL','H 02 (H02_LP)','H02','H02_LP','Inferir o sentido de uma palavra ou expressão.'),
('3º ano','LP','mais','ESTADUAL','H 03 (H03_LP)','H03','H03_LP','Inferir uma informação implícita em um texto.'),
('3º ano','LP','mais','ESTADUAL','H 06 (H06_LP)','H06','H06_LP','Interpretar textos com auxílio de material gráfico diverso (propagandas, quadrinhos, fotos, etc.).'),
('3º ano','LP','mais','ESTADUAL','H 01 (H01_LP)','H01','H01_LP','Localizar informações explícitas em um texto.'),
('3º ano','LP','mais','ESTADUAL','H 17 (H18_LP)','H17','H18_LP','Reconhecer o efeito de sentido decorrente do uso da pontuação e de outras notações.'),
('3º ano','LP','mais','ESTADUAL','H 09 (H09_LP)','H09','H09_LP','Reconhecer posições distintas entre duas ou mais opiniões relativas ao mesmo fato ou ao mesmo tema.'),
('2º ano','MT','parceiro','ESTADUAL','H 20 (D102_M)','H20','D102_M','Identificar a representação algébrica ou gráfica de uma função logarítmica.'),
('2º ano','MT','parceiro','ESTADUAL','H 12 (D069_M)','H12','D069_M','Reconhecer a representação algébrica de uma função polinomial de 1º grau a partir dos dados apresentados em uma tabela.'),
('2º ano','MT','parceiro','ESTADUAL','H 14 (D073_M)','H14','D073_M','Corresponder a representação algébrica e gráfica de uma função polinomial de 2º grau.'),
('6º ano','MT','parceiro','ESTADUAL','H 11 (D027_M)','H11','D027_M','Corresponder números racionais à sua escrita por extenso.'),
('6º ano','MT','parceiro','ESTADUAL','H 07 (D018_M)','H07','D018_M','Determinar termos ausentes em sequências de números naturais.'),
('6º ano','MT','parceiro','ESTADUAL','H 03 (D004_M)','H03','D004_M','Executar adição ou subtração com números naturais.'),
('6º ano','MT','parceiro','ESTADUAL','H 01 (D001_M)','H01','D001_M','Identificar a localização ou a movimentação de pessoas ou objetos em uma representação plana do espaço.'),
('6º ano','MT','parceiro','ESTADUAL','H 04 (D009_M)','H04','D009_M','Identificar informações apresentadas em tabelas ou gráficos.'),
('6º ano','MT','parceiro','ESTADUAL','H 05 (D010_M)','H05','D010_M','Identificar representações de figuras bidimensionais.'),
('6º ano','MT','parceiro','ESTADUAL','H 02 (D002_M)','H02','D002_M','Reconhecer características do sistema de numeração decimal.'),
('6º ano','MT','parceiro','ESTADUAL','H 09 (D021_M)','H09','D021_M','Utilizar informações apresentadas em tabelas ou gráficos na resolução de problemas.'),
('6º ano','MT','parceiro','ESTADUAL','H 14 (D031_M)','H14','D031_M','Utilizar números naturais e racionais, envolvendo diferentes significados da adição ou da subtração, na resolução de problemas.'),
('6º ano','MT','parceiro','ESTADUAL','H 15 (D032_M)','H15','D032_M','Utilizar números naturais e racionais, envolvendo diferentes significados da multiplicação ou da divisão, na resolução de problemas.'),
('7º ano','MT','parceiro','ESTADUAL','H 12 (D040_M)','H12','D040_M','Identificar os elementos constitutivos de um gráfico, como título, eixos, legendas, fontes e datas.'),
('7º ano','MT','parceiro','ESTADUAL','H 01 (D010_M)','H01','D010_M','Identificar representações de figuras bidimensionais.'),
('7º ano','MT','parceiro','ESTADUAL','H 09 (D031_M)','H09','D031_M','Utilizar números naturais e racionais, envolvendo diferentes significados da adição ou da subtração, na resolução de problemas.'),
('7º ano','MT','parceiro','ESTADUAL','H 10 (D032_M)','H10','D032_M','Utilizar números naturais e racionais, envolvendo diferentes significados da multiplicação ou da divisão, na resolução de problemas.'),
('9º ano','MT','parceiro','ESTADUAL','H 10 (D052_M)','H10','D052_M','Associar uma equação linear de 1º grau com duas incógnitas a uma reta no plano cartesiano.'),
('9º ano','MT','parceiro','ESTADUAL','H 18 (D094_M)','H18','D094_M','Executar cálculos entre números representados em forma de potência, com expoentes inteiros, expressando o resultado em notação científica.'),
('9º ano','MT','parceiro','ESTADUAL','H 19 (D095_M)','H19','D095_M','Identificar, no plano cartesiano, a solução de um sistema de equações do 1º grau com duas equações e duas incógnitas.'),
('9º ano','MT','parceiro','ESTADUAL','H 20 (D096_M)','H20','D096_M','Reconhecer a condição de existência de um triângulo.'),
('9º ano','MT','parceiro','ESTADUAL','H 14 (D072_M)','H14','D072_M','Utilizar sistema de equações polinomiais de 1º grau na resolução de problema.'),
('1º ano','MT','parceiro','ESTADUAL','H 08 (D058_M)','H08','D058_M','Corresponder figuras tridimensionais às suas vistas.'),
('1º ano','MT','parceiro','ESTADUAL','H 16 (D098_M)','H16','D098_M','Identificar uma relação entre conjuntos que representa uma função.'),
('1º ano','MT','parceiro','ESTADUAL','H 10 (D061_M)','H10','D061_M','Identificar, dentre gráficos diversos, o gráfico que representa uma relação de dependência unívoca entre duas variáveis.'),
('1º ano','MT','parceiro','ESTADUAL','H 17 (D099_M)','H17','D099_M','Utilizar a razão entre duas grandezas de espécies diferentes, na resolução de problemas.'),
('1º ano','MT','parceiro','ESTADUAL','H 11 (D062_M)','H11','D062_M','Utilizar números reais, em notação científica, na resolução de problema.'),
('1º ano','MT','parceiro','ESTADUAL','H 14 (D072_M)','H14','D072_M','Utilizar sistema de equações polinomiais de 1º grau na resolução de problema.'),
('2º ano','MT','parceiro','ESTADUAL','H 21 (D104_M)','H21','D104_M','Reconhecer polígonos semelhantes usando os critérios de semelhança.'),
('3º ano','MT','parceiro','ESTADUAL','H 17 (D112_M)','H17','D112_M','Reconhecer o seno, cosseno e a tangente como razões entre os lados de um triângulo retângulo.'),
('3º ano','MT','parceiro','ESTADUAL','H 16 (D111_M)','H16','D111_M','Resolver problema envolvendo semelhança de triângulo.'),
('3º ano','MT','parceiro','ESTADUAL','H 13 (D108_M)','H13','D108_M','Resolver problemas envolvendo juros compostos.'),
('3º ano','MT','parceiro','ESTADUAL','H 19 (D114_M)','H19','D114_M','Resolver problemas envolvendo noções de análise combinatória.'),
('6º ano','MT','prova-parana','ESTADUAL','H 09 (D015_M)','H09','D015_M','Corresponder cédulas e/ou moedas do Sistema Monetário Brasileiro.'),
('6º ano','MT','prova-parana','ESTADUAL','H 08 (D014_M)','H08','D014_M','Corresponder o horário de início e de término com o intervalo de duração de um evento ou acontecimento.'),
('6º ano','MT','prova-parana','ESTADUAL','H 22 (D082_M)','H22','D082_M','Executar a medição de grandezas por meio de medidas convencionais ou não.'),
('6º ano','MT','prova-parana','ESTADUAL','H 04 (D004_M)','H04','D004_M','Executar adição ou subtração com números naturais.'),
('6º ano','MT','prova-parana','ESTADUAL','H 23 (D086_M)','H23','D086_M','Executar multiplicação ou divisão com números naturais.'),
('6º ano','MT','prova-parana','ESTADUAL','H 01 (D001_M)','H01','D001_M','Identificar a localização ou a movimentação de pessoas ou objetos em uma representação plana do espaço.'),
('6º ano','MT','prova-parana','ESTADUAL','H 03 (D003_M)','H03','D003_M','Identificar composições ou decomposições de números naturais.'),
('6º ano','MT','prova-parana','ESTADUAL','H 06 (D009_M)','H06','D009_M','Identificar informações apresentadas em tabelas ou gráficos.'),
('6º ano','MT','prova-parana','ESTADUAL','H 07 (D010_M)','H07','D010_M','Identificar representações de figuras bidimensionais.'),
('6º ano','MT','prova-parana','ESTADUAL','H 02 (D002_M)','H02','D002_M','Reconhecer características do sistema de numeração decimal.'),
('6º ano','MT','prova-parana','ESTADUAL','H 18 (D041_M)','H18','D041_M','Relacionar uma figura plana com sua ampliação ou redução, com o apoio de malha quadriculada.'),
('6º ano','MT','prova-parana','ESTADUAL','H 24 (D120_M)','H24','D120_M','Utilizar a escrita decimal de cédulas e moedas do sistema monetário brasileiro, na resolução de problema.'),
('9º ano','MT','mais','ESTADUAL','H 37 (D37)','H37','D37','Associar informações apresentadas em listas e/ou tabelas simples aos gráficos que as representam e vice-versa.'),
('9º ano','MT','mais','ESTADUAL','H 30 (D30)','H30','D30','Calcular o valor numérico de uma expressão algébrica.'),
('9º ano','MT','mais','ESTADUAL','H 21 (D18)','H21','D18','Efetuar cálculos com números inteiros, envolvendo as operações (adição, subtração, multiplicação, divisão, potenciação).'),
('9º ano','MT','mais','ESTADUAL','H 25 (D25)','H25','D25','Efetuar cálculos que envolvam operações com números racionais (adição, subtração, multiplicação, divisão, potenciação).'),
('9º ano','MT','mais','ESTADUAL','H 17 (D16)','H17','D16','Identificar a localização de números inteiros na reta numérica.'),
('9º ano','MT','mais','ESTADUAL','H 16 (D17)','H16','D17','Identificar a localização de números racionais na reta numérica.'),
('9º ano','MT','mais','ESTADUAL','H 01 (D01)','H01','D01','Identificar a localização/movimentação de objeto em mapas, croquis e outras representações gráficas.'),
('9º ano','MT','mais','ESTADUAL','H 35 (D35)','H35','D35','Identificar a relação entre as representações algébrica e geométrica de um sistema de equações do 1º grau.'),
('9º ano','MT','mais','ESTADUAL','H 20 (D22)','H20','D22','Identificar fração como representação que pode estar associada a diferentes significados.'),
('9º ano','MT','mais','ESTADUAL','H 02 (D02)','H02','D02','Identificar propriedades comuns e diferenças entre figuras bidimensionais e tridimensionais, relacionando-as com as suas planificações.'),
('9º ano','MT','mais','ESTADUAL','H 04 (D03)','H04','D03','Identificar propriedades de triângulos pela comparação de medidas de lados e ângulos.'),
('9º ano','MT','mais','ESTADUAL','H 03 (D04)','H03','D04','Identificar relação entre quadriláteros por meio de suas propriedades.'),
('9º ano','MT','mais','ESTADUAL','H 09 (D09)','H09','D09','Interpretar informações apresentadas por meio de coordenadas cartesianas.'),
('9º ano','MT','mais','ESTADUAL','H 05 (D05)','H05','D05','Reconhecer a conservação ou modificação de medidas dos lados, do perímetro, da área em ampliação e/ou redução de figuras poligonais usando malhas quadriculadas.'),
('9º ano','MT','mais','ESTADUAL','H 19 (D21)','H19','D21','Reconhecer as diferentes representações de um número racional.'),
('9º ano','MT','mais','ESTADUAL','H 24 (D24)','H24','D24','Reconhecer as representações decimais dos números racionais como uma extensão do sistema de numeração decimal, identificando a existência de "ordens" como décimos, centésimos e milésimos.'),
('9º ano','MT','mais','ESTADUAL','H 11 (D11)','H11','D11','Reconhecer círculo/circunferência, seus elementos e algumas de suas relações.'),
('9º ano','MT','mais','ESTADUAL','H 07 (D07)','H07','D07','Reconhecer que as imagens de uma figura construída por uma transformação homotética são semelhantes, identificando propriedades e/ou medidas que se modificam ou não se alteram.'),
('9º ano','MT','mais','ESTADUAL','H 22 (D20)','H22','D20','Resolver problema com números inteiros envolvendo as operações (adição, subtração, multiplicação, divisão, potenciação).'),
('9º ano','MT','mais','ESTADUAL','H 18 (D19)','H18','D19','Resolver problema com números naturais, envolvendo diferentes significados das operações (adição, subtração, multiplicação, divisão, potenciação).'),
('9º ano','MT','mais','ESTADUAL','H 26 (D26)','H26','D26','Resolver problema com números racionais envolvendo as operações (adição, subtração, multiplicação, divisão, potenciação).'),
('9º ano','MT','mais','ESTADUAL','H 36 (D36)','H36','D36','Resolver problema envolvendo informações apresentadas em tabelas e/ou gráficos.'),
('9º ano','MT','mais','ESTADUAL','H 15 (D14)','H15','D14','Resolver problema envolvendo noções de volume.'),
('9º ano','MT','mais','ESTADUAL','H 14 (D13)','H14','D13','Resolver problema envolvendo o cálculo de área de figuras planas.'),
('9º ano','MT','mais','ESTADUAL','H 13 (D12)','H13','D12','Resolver problema envolvendo o cálculo de perímetro de figuras planas.'),
('9º ano','MT','mais','ESTADUAL','H 31 (D31)','H31','D31','Resolver problema que envolva equação do 2º grau.'),
('9º ano','MT','mais','ESTADUAL','H 28 (D28)','H28','D28','Resolver problema que envolva porcentagem.'),
('9º ano','MT','mais','ESTADUAL','H 29 (D29)','H29','D29','Resolver problema que envolva variação proporcional, direta ou inversa, entre grandezas.'),
('9º ano','MT','mais','ESTADUAL','H 08 (D08)','H08','D08','Resolver problema utilizando propriedades dos polígonos (soma de seus ângulos internos, número de diagonais, cálculo da medida de cada ângulo interno nos polígonos regulares).'),
('9º ano','MT','mais','ESTADUAL','H 12 (D15)','H12','D15','Resolver problema utilizando relações entre diferentes unidades de medida.'),
('3º ano','MT','mais','ESTADUAL','H 23 (H40_MT)','H23','H40_MT','Calcular a probabilidade de um evento.'),
('3º ano','MT','mais','ESTADUAL','H 21 (H38_MT)','H21','H38_MT','Determinar a solução de um sistema linear associando-o a uma matriz.'),
('3º ano','MT','mais','ESTADUAL','H 04 (H08_MT)','H04','H08_MT','Identificar figuras semelhantes mediante o reconhecimento de relações de proporcionalidade.'),
('3º ano','MT','mais','ESTADUAL','H 20 (H37_MT)','H20','H37_MT','Identificar gráficos de funções trigonométricas (seno, cosseno, tangente) reconhecendo suas propriedades.'),
('3º ano','MT','mais','ESTADUAL','H 17 (H28_MT)','H17','H28_MT','Identificar o gráfico que representa uma situação descrita em um texto.'),
('3º ano','MT','mais','ESTADUAL','H 08 (H14_MT)','H08','H14_MT','Interpretar geometricamente os coeficientes da equação de uma reta.'),
('3º ano','MT','mais','ESTADUAL','H 05 (H09_MT)','H05','H09_MT','Reconhecer aplicações das relações métricas do triângulo retângulo em um problema que envolva figuras planas ou espaciais.'),
('3º ano','MT','mais','ESTADUAL','H 15 (H25_MT)','H15','H25_MT','Reconhecer expressão algébrica que representa uma função a partir de uma tabela.'),
('3º ano','MT','mais','ESTADUAL','H 06 (H10_MT)','H06','H10_MT','Relacionar diferentes poliedros ou corpos redondos com suas planificações ou vistas.'),
('3º ano','MT','mais','ESTADUAL','H 24 (H41_MT)','H24','H41_MT','Resolver problema com dados apresentados em tabelas ou gráficos.'),
('3º ano','MT','mais','ESTADUAL','H 03 (H07_MT)','H03','H07_MT','Resolver problema com números racionais, envolvendo as operações (adição, subtração, multiplicação, divisão, potenciação).'),
('3º ano','MT','mais','ESTADUAL','H 22 (H39_MT)','H22','H39_MT','Resolver problema de contagem utilizando o princípio multiplicativo ou noções de permutação simples, arranjo simples e/ou combinação simples.'),
('3º ano','MT','mais','ESTADUAL','H 11 (H20_MT)','H11','H20_MT','Resolver problema envolvendo a área total e/ou volume de um sólido (prisma, pirâmide, cilindro, cone, esfera).'),
('3º ano','MT','mais','ESTADUAL','H 14 (H24_MT)','H14','H24_MT','Resolver problema envolvendo equação do 2° grau.'),
('3º ano','MT','mais','ESTADUAL','H 01 (H03_MT)','H01','H03_MT','Resolver problema envolvendo noções de volume.'),
('3º ano','MT','mais','ESTADUAL','H 10 (H19_MT)','H10','H19_MT','Resolver problema envolvendo o cálculo de área de figuras planas.'),
('3º ano','MT','mais','ESTADUAL','H 18 (H29_MT)','H18','H29_MT','Resolver problema envolvendo P.A./P.G., dada a fórmula do termo geral.'),
('3º ano','MT','mais','ESTADUAL','H 16 (H26_MT)','H16','H26_MT','Resolver problema envolvendo uma função do 1° grau.'),
('3º ano','MT','mais','ESTADUAL','H 13 (H23_MT)','H13','H23_MT','Resolver problema que envolva porcentagem.'),
('3º ano','MT','mais','ESTADUAL','H 07 (H12_MT)','H07','H12_MT','Resolver problema que envolva razões trigonométricas no triângulo retângulo (seno, cosseno, tangente).'),
('3º ano','MT','mais','ESTADUAL','H 12 (H22_MT)','H12','H22_MT','Resolver problema que envolva variação proporcional, direta ou inversa, entre grandezas.'),
('3º ano','MT','mais','ESTADUAL','H 02 (H04_MT)','H02','H04_MT','Resolver problema utilizando relações entre diferentes unidades de medida.');

-- tipo_prova obrigatorio e restrito aos 3 sistemas
ALTER TABLE componentes_habilidades
  ALTER COLUMN tipo_prova SET NOT NULL;

ALTER TABLE componentes_habilidades
  DROP CONSTRAINT IF EXISTS componentes_habilidades_tipo_prova_check;
ALTER TABLE componentes_habilidades
  ADD CONSTRAINT componentes_habilidades_tipo_prova_check
  CHECK (tipo_prova IN ('prova-parana','mais','parceiro'));

-- Chave natural: um descritor por (tipo_prova, ano_escolar, componente, posicao)
ALTER TABLE componentes_habilidades
  DROP CONSTRAINT IF EXISTS componentes_habilidades_natural_key;
ALTER TABLE componentes_habilidades
  ADD CONSTRAINT componentes_habilidades_natural_key
  UNIQUE (tipo_prova, ano_escolar, componente, posicao);

CREATE INDEX IF NOT EXISTS idx_componentes_habilidades_lookup
  ON componentes_habilidades (tipo_prova, ano_escolar, componente, posicao);
